### ISSUE TITLE
hit catcher need to be customize and form groups for pandas. Like Jr  Panda.

### ISSUE THREAD

**Issue by balajicap** [brandonhellman/mturk-suite#10]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by brandonhellman** [comment]
Can you please elaborate? Keep in mind this is not meant to be a copy Panda Crazy.

**Comment by balajicap** [comment]
I want to place panda'a as my wish or requester wise. It is hard to use
arrow marks for arrange panda's. if it is flexible to move, it will helpful
to run immediately. Grouping or favorite GID system also helpful. that's
why i'm asking, i want collect to hits, like requester id wise or include
list wise.  if i put requester id into the catcher, it will collect all
hits of that requester.we need like this..Please do needful for my queries.
if it possible. thank you for immediate response . thank you for support
workers...

**Comment by brandonhellman** [comment]
Added to projects. 

https://github.com/Kadauchi/mturk-suite/projects/1#card-6990607
https://github.com/Kadauchi/mturk-suite/projects/1#card-6990628
