### ISSUE TITLE
Ideas to improve HIT Catcher

### ISSUE THREAD

**Issue by mjh0527** [brandonhellman/mturk-suite#103]
## Expected Behavior 
 Would be nice to have options to remove items from HIT catcher rather than one at a time.

## Current Behavior
Currently you click the 'x' on the item and confirm.  It would be nice to have a 'delete all catchers' item or some rules i.e. delete after x number of attempts or time. Or after catching one delete after x minutes.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
 HITs I add at the beginning of my session continue to try to be caught.  After a certain amount of time I'm pretty sure I'm not going to catch that HIT and have to delete it manually.  The more HITs the catcher is attempting to catch the less tries it gets per HIT per amount of time which reduces the likelihood of catching the most recently added HITs to the catcher.  If I could set up the catcher to clear out HITs after a certain amount of tries or time then it would save me the time from having to go in and manually deleting them.

## Your Environment

* Version used:
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows 7

**Comment by mjh0527** [comment]
Sorry, just saw the 'delete all' was already recommended.  Thanks for the great tools!

**Comment by brandonhellman** [comment]
The documentation isn't good on HIT Catcher yet for various reasons, but you can `Ctrl+Click` on watcher to select multiple and then hit the `Delete` key to delete all selected watchers.
