### ISSUE TITLE
HIT catcher not as effective?

### ISSUE THREAD

**Issue by nonagonagon** [brandonhellman/mturk-suite#104]
Hi, very sorry if this is addressed elsewhere-- 

I have noticed that my HIT catcher has not been as effective at catching HITs as it has been since I started using it a little over a month ago. I thought at first it was just me trying to catch too many at a time, but even with one HIT running, it absolutely will not catch the HIT, regardless of how popular it is. 

What am I doing wrong? Anyone else reporting this? Any tips to improve my rates of catching HITs? Thanks for the help!

**Comment by brandonhellman** [comment]
What is the speed setting at?

**Comment by Harni06** [comment]
Me too facing the same problem now. My speed setting is 100 ms. I used the same speed from the beginning itself. But now only I got very least hits when compare to my other friends.

**Comment by JrRandy** [comment]
100ms is wayyy too low.  You need to be around 900-1000.  100ms will cause more Page Request Errors than anything and prevent anything being caught.  100ms is 10 page requests per second.  Amazon does not allow that rate of page requests.
