### ISSUE TITLE
Auto accept check box

### ISSUE THREAD

**Issue by shaqsbit** [brandonhellman/mturk-suite#105]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
The auto accepts next hit checkbox not active.  No changes made in the settings, few others are also facing the same issue.

Please advise.

**Comment by JrRandy** [comment]
There appears to have been another change that mTurk has made.  It appears to now hold your setting from your last hit.  If you unchecked "Auto-Accept", it will remain unchecked until you check it again.  Once you submit a hit with it checked, it will remain checked until you submit a hit with it unchecked.

**Comment by brandonhellman** [comment]
Thanks for the heads up. Looks like I'll be able to just remove everything related to managing the checkbox state since MTurk finally has their own solution.
