### ISSUE TITLE
Since the new update the accept one and panda buttons are missing after you fail to accept a hit from hit finder

### ISSUE THREAD

**Issue by Rainingcatsnstuff** [brandonhellman/mturk-suite#107]
Usually the panda and accept one buttons show up on the page after you click on a hit to accept it from the hit finder. Since the update they are no longer there, making it so you have to go back to the hit finder and right click to get the options.

**Comment by brandonhellman** [comment]
Is this still happening?

**Comment by Rainingcatsnstuff** [comment]
No, it stopped several hours later.
