### ISSUE TITLE
Improvement: Hitfinder Hits Hard to Click On (Bouncing Due to Blocked Hits)

### ISSUE THREAD

**Issue by TurkWarrior** [brandonhellman/mturk-suite#108]
## Expected Behavior

We should be able to click on the HITS in Hitfinder without having to chase them down on the screen when they bounce up and down.

## Current Behavior

When I block HITS, the blocked Hits section in Hitfinder tends to expand and shrink based on invisible HITS being blocked. I say "invisible" because it doesn't show the HITS that are being blocked, but it still adds a grey or white line in the space where the blocked HIT would normally show so this causes that whole section to expand, which bounces the HITS below it in the "Logged HITs" section.  (I've attached a screenshot to show the section I'm talking about)
![hitfinder improvement](https://user-images.githubusercontent.com/39699229/42212001-be3ebf30-7e69-11e8-8550-c517430e62fb.jpg)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Often times, I'll hear a beep indicating that a new HIT has shown up in Hitfinder, and I'll race to click on it so that I can accept it before others snatch it up, but I end up chasing it down on my screen because it will bounce up and down quickly and I can't seem to click on it fast enough with my mouse. Because of this, I've lost so many HITS that I normally would have clicked on quick enough if the HITS had stayed in one place.

## Your Environment

* Version used: Mturk Suite V2.3.7
* Browser Name and version: Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by brandonhellman** [comment]
I believe most people work around this by either having a slower delay or by collapsing the Recent HITs section since any new HITs always show at the top of the Logged HITs section.

I'm open to specific suggestion on how to improve the jumping,

**Comment by TurkWarrior** [comment]
Ok I'm an idiot. Just found the button to collapse it after you mentioned it. #mindblown.   Disregard. Thanks
