### ISSUE TITLE
Workspace Expander no longer focuses iframe?

### ISSUE THREAD

**Issue by EternalTech** [brandonhellman/mturk-suite#109]
Not sure if it is just me but I can't get the iframe to focus anymore, I have to click in it first to focus it.

**Comment by brandonhellman** [comment]
I've heard some other being affected too (I am not currently), not sure if its a browser issue, MTS issue or some other random thing. Mind providing your browser + browser version?

**Comment by EternalTech** [comment]
Thanks for the reply, I'm using Chrome Version 67.0.3396.99. (Should be the most recent update)

**Comment by dgramstorff** [comment]
Roughly 10% of the time, I need to click to focus using Firefox 61.0.1 (64-bit).  I have not noticed the issue in Chrome Version 67.0.3396.99 (Official Build) (64-bit).

When other apps are using a lot of CPU, this happens much more often.  The tab is fully loaded in these cases.
