### ISSUE TITLE
Screen jumps around

### ISSUE THREAD

**Issue by Glowarr** [brandonhellman/mturk-suite#110]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
When I try to use Hit Finder the screen jumps making it very hard to click on a hit I'm interested in. By the time I actually click on the hit, which takes many tries, there are no more of that hit to take. Kind of hard to make money when Hit finder acts up. I am  using Chrome, Not sure of the version. Lenovo laptop with Windows 7 Professional. 

I look forward to hearing from you so this can be fixed.

**Comment by brandonhellman** [comment]
Touched on this in here.
https://github.com/Kadauchi/mturk-suite/issues/108
