### ISSUE TITLE
Tracker overview not updating

### ISSUE THREAD

**Issue by noniem** [brandonhellman/mturk-suite#111]
Lately the 'tracker overview' has stopped updating, even after syncing. 
Before, when the sync option was chosen both the 'today's overview' and the 'tracker overview' would update. 

Now, only 'today's overview' updates but the 'tracker overview' columns remains blank with dashes

I'm using the latest version of Chrome with Windows 10, on a laptop

**Comment by brandonhellman** [comment]
Can you open the console log ` Ctrl+Shift+J ` and see if there are any errors reported in there? If there is an error then what is it, either copy the text or provide a screenshot.
