### ISSUE TITLE
Block list import not working

### ISSUE THREAD

**Issue by workwithjoemiranda** [brandonhellman/mturk-suite#112]
## Expected Behavior
 Import block list from JSON file. 

## Current Behavior
 Nothing happens after importing file. Been working just fine until today. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by brandonhellman** [comment]
Can you open the console log `Ctrl+Shift+J` and see if there are any errors (red) reported in there after you try to import the Blocklist and it fails.? If there is an error then what is it, either copy the text or provide a screenshot.

**Comment by workwithjoemiranda** [comment]
@Kadauchi There were a bunch of errors earlier. I reloaded MTS and it seems to be working correctly now though. So it is resolved for me now.

**Comment by brandonhellman** [comment]
Thanks for following up. I'll keep an eye out in case this pops up for anyone else in the future.
