### ISSUE TITLE
Feature Request: Add Catcher Buttons and Have Requester/Hit info all on one pop up

### ISSUE THREAD

**Issue by workwithjoemiranda** [brandonhellman/mturk-suite#113]
Is there any way you could add Catch Once and Catch Multiple buttons for the Hit Catcher to Hit Finder like I have below? This feature is on Hit Forker for Panda Crazy. Was wondering if you could do this for the Hit Catcher on MTS.

![once and multiple buttons](https://user-images.githubusercontent.com/32000146/42662448-4190062a-85f7-11e8-94d1-9779cef2c71e.jpg)

And/Or is there any way to integrate the Requester Ratings and Hit Info on to one page instead of having to click two different buttons? This would allow you to get rid of the Info Button and have just the ratings button to click. Additionally instead of having to take a third action and right click a hit to add it to Hit Catcher, could there be a way to also add Catch Once and Catch Multiple buttons at the bottom of this same pop out? This way all the info is on one place and will save everyone a lot of time and hassle. I have a problem with clicking on one requester ratings for a hit but not clicking the right one all the time because it moves with every new hit logged. So I end up wasting time looking at info for the wrong hit. This would eliminate all of that and would make adding hits to the Catcher and researching hits a heck of a lot easier for everyone. 

![reviews](https://user-images.githubusercontent.com/32000146/42662095-e96ef75e-85f5-11e8-8fcf-3001c4d2e67f.jpg)

P.S. Even if these features are not possible, I just want to personally thank you so much for the time and dedication you have taken creating this amazing tool for us all to use! You are a lifesaver!

**Comment by brandonhellman** [comment]
Actually, yes to all.

The reason why there are no panda/once buttons on the hit rows is because of limited horizontal space and because you can right click the links to add them (albeit this is slower).

Combining the Requester Ratings and Hit Info onto the same modal will allow me to remove a button and that should be enough space to make it not clutter by adding the panda/once buttons.

**Comment by workwithjoemiranda** [comment]
That would be awesome to have these! That's what I was thinking, simplification while avoiding clutter.
