### ISSUE TITLE
Requesting option to disable site search in url (when "mturk" is typed first)

### ISSUE THREAD

**Issue by dirtyfumbles** [brandonhellman/mturk-suite#114]
## Expected Behavior
If I type "mturk" into the url bar, and press space afterwards (which is normal because spaces exist between words), it alters the url to search the mturk listings with the words that follow.   My suggestion is to have an option to disable this feature on the grounds that is more annoying than useful.

## Context
Its pretty annoying when trying to search for mturk related stuff.

## Your Environment

Using Chrome on Win 8.1

**Comment by dirtyfumbles** [comment]
reply

**Comment by brandonhellman** [comment]
I don't believe the omnibox search can be optional, its either included or not. 

This is either being dropped or changed to something like `?mturk` instead in v3.

**Comment by dirtyfumbles** [comment]
Brilliant.  Thank you.
