### ISSUE TITLE
Not a major issue but yesterday MTS Hit Catcher started acting strange in that when the screen is set to 100% it jumps and wiggles if I click any button (Catch, Sound, Pause, etc.) I don't have this problem if the screen is set to 90 or 110%. Just curious what's causing this behavior at 100% and if there's a fix for it.

### ISSUE THREAD

**Issue by LauraHarding** [brandonhellman/mturk-suite#115]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by brandonhellman** [comment]
What browser and browser version are you using?

**Comment by LauraHarding** [comment]
As far as I can tell it's Chrome 67.



-----Original Message-----

**Comment by sryan200** [comment]
I actually came on here for this specific reason and see that this has already been brought up.  Mturk Suite started becoming really glitchy for me about a day ago as well.  It has been really slow and jumpy.  I never had this issue until yesterday
