### ISSUE TITLE
Feature request: Better 'qualified to work on' filter

### ISSUE THREAD

**Issue by SharkROAR** [brandonhellman/mturk-suite#117]
Since I am not a resident of the United States I am obviously not able to accept a lot of HITs that are restricted by location. The only option to hide these is to hide all HITs I'm not qualified to work on, which would mean I'd miss out on tasks that I could potentially qualify for. A simple filter that only lists HITs that I can actually qualify for, and those I'm already qualified for, would improve my experience a lot.

Thanks in advance.

**Comment by brandonhellman** [comment]
@xspager took care of this with https://github.com/Kadauchi/mturk-suite/pull/125
