### ISSUE TITLE
Catcher not catching

### ISSUE THREAD

**Issue by cls221** [brandonhellman/mturk-suite#118]
I am not catching HITs that I know for a fact are available. I usually catch at a regular rate. I have not caught one hit today. When I do ctrl+shift+j I get errors.

server responded with a status of 422 (Unprocessable Entity)
worker.mturk.com/projects/345DFELIPBIZAEOSW8RKB0T5NBBX0V/tasks/accept_random?format=json:1 Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
worker.mturk.com/projects/3WRXIMH6F27S8QAUA127HNTF7BPL4Q/tasks/accept_random?format=json:1 Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
worker.mturk.com/projects/3R35RPFD8KHU8U7J60L3VSQCQ56P12/tasks/accept_random?format=json:1 Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
worker.mturk.com/projects/3LHGJL34ALZJCFDEA482BBVR86WO29/tasks/accept_random?format=json:1 Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
worker.mturk.com/projects/345DFELIPBIZAEOSW8RKB0T5NBBX0V/tasks/accept_random?format=json:1 Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
worker.mturk.com/projects/3WRXIMH6F27S8QAUA127HNTF7BPL4Q/tasks/accept_random?format=json:1 Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
worker.mturk.com/projects/3R35RPFD8KHU8U7J60L3VSQCQ56P12/tasks/accept_random?format=json:1 Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
worker.mturk.com/projects/3LHGJL34ALZJCFDEA482BBVR86WO29/tasks/accept_random?format=json:1 Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
hit_catcher.js:518 GET https://worker.mturk.com/projects/345DFELIPBIZAEOSW8RKB0T5NBBX0V/tasks/accept_random?format=json 422 (Unprocessable Entity)
catcherRun @ hit_catcher.js:518
hit_catcher.js:518 GET https://worker.mturk.com/projects/3WRXIMH6F27S8QAUA127HNTF7BPL4Q/tasks/accept_random?format=json 422 (Unprocessable Entity)
catcherRun @ hit_catcher.js:518
setTimeout (async)
catcherRun @ hit_catcher.js:559
async function (async)
catcherRun @ hit_catcher.js:503
hit_catcher.js:518 GET https://worker.mturk.com/projects/3R35RPFD8KHU8U7J60L3VSQCQ56P12/tasks/accept_random?format=json 422 (Unprocessable Entity)

## Your Environment
* Version used:
* Browser Name and version: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Laptop

**Comment by brandonhellman** [comment]
The 422 (Unprocessable Entity) is expect as that is how their server returns for a missed HIT. Something else must be wrong. Are there any other errors that you can see?
