### ISSUE TITLE
hit finder is blocking some of my hits even when I delete block list, hits are still being blocked

### ISSUE THREAD

**Issue by cpweducator** [brandonhellman/mturk-suite#119]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by cpweducator** [comment]
ok I think I just fixed it. I uninstalled and reinstalled and it seems to be working fine now

**Comment by brandonhellman** [comment]
I'll still look into it, thanks for the bug report.
