### ISSUE TITLE
Hit Catcher Not Making Sound --Chrome

### ISSUE THREAD

**Issue by Capnfrance** [brandonhellman/mturk-suite#120]
On the Chrome version of MTurk Suite, the HIT Catcher does not make a sound when it catches a hit. 

## Expected Behavior
When it catches a hit, the hit catcher should make a sound. Previously it was text to speech "hit caught: <requester name>.

## Current Behavior
The hit catcher does not make a sound when catching a hit. 

## Steps to Reproduce (for bugs)
At least for me, it happens every time I catch a hit with the hit catcher. 

## Context
I'm trying to catch hits without constantly looking at my queue or the hit catcher. 

## Your Environment
Newest version, Chrome, on Windows 10.

**Comment by Capnfrance** [comment]
Never mind, it was actually a Windows issue. I hadn't noticed that Text To Speech wasn't working on anything, because this is the only thing I use text to speech on.

**Comment by JAISAIRAM-1** [comment]
The hit catcher does not make a sound when catching a hit.

**Comment by brandonhellman** [comment]
@JAISAIRAM-1 try rebooting Chrome.
