### ISSUE TITLE
Hit Tracker trying to use Chrome address from Dashboard Earnings numbers

### ISSUE THREAD

**Issue by Turtlefemm** [brandonhellman/mturk-suite#122]
When I click on the Earnings at the upper left side of my Mturk dashboard on Firefox, HIT tracker attempts to use the Chrome version address, chrome-extension://{dd19b0aa-6eee-4a10-a6bc-361a163f7821}/hit_tracker/hit_tracker.html instead of the Firefox version and, of course, goes to an "address isn't understood" page. The address is correct when using the MTS button.  I uninstalled and reinstalled MTS before realizing it was trying to use the wrong web address.

**Comment by brandonhellman** [comment]
I wonder if Firefox must have updated something. I'll get a fix done and released in the next 24 hours for this.
