### ISSUE TITLE
MTS HIT Tracker not syncing

### ISSUE THREAD

**Issue by Trucker5** [brandonhellman/mturk-suite#130]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by Trucker5** [comment]
HIT Tracker is not syncing my account at all in Chrome. It says "fetching dashboard" and won't go any further. When I run a sync in Firefox, it will sync but the "Pending Earnings" and "Approved Waiting Payment" totals are incorrect.

**Comment by madhanprashanna** [comment]
bro hit tracker not sync properly
it stuck in HIT sync dasboard always

**Comment by brandonhellman** [comment]
@madhanprashanna  Are you logged in?
