### ISSUE TITLE
Hit Tracker Info Won't Update

### ISSUE THREAD

**Issue by Tilunas** [brandonhellman/mturk-suite#133]
Having an issue with my Hit Tracker where it says I have a Hit that is Approved Waiting Payment when I don't. I've tried syncing for a couple days now but it still won't update.

**Comment by brandonhellman** [comment]
You're using the 45 day sync correct? If you are then the HIT is outside the last 45 days and the only way to fix that would be to export the database and then import it (no need to clear out any data).

**Comment by Tilunas** [comment]
Yeah I was using the 45 day sync. Exporting and then Importing fixed it, thanks!
