### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by xspager** [brandonhellman/mturk-suite#137]
@Kadauchi, sorry, I messed up. I failed to notice the merge I made on the pull request to fix the logout message caused a regression https://github.com/Kadauchi/mturk-suite/commit/3c11b027a7a588843202171f3d252f2675ea68f6

Sorry 😢

**Comment by brandonhellman** [comment]
No worries. I'm still pretty new to git anyways so anything is just more learning.

**Comment by xspager** [comment]
OK, I realized what happened. Actually nothing went wrong, I was a bit (a lot) under the weather and failed to see you made some changes (https://github.com/Kadauchi/mturk-suite/commit/026c69f0d2f88d11db5fb471ed403eac345898e4) and thought I did something wrong merging stuff when this changes appeared. 👍 

What I actually did made a mistake and left a console.log call I used to debug, I just made a new pull request but not hurry with this one.
