### ISSUE TITLE
After I Did the Latest Update, Hit Catcher Started Having An Error

### ISSUE THREAD

**Issue by nathan012** [brandonhellman/mturk-suite#139]
## Expected Behavior

After I updated my Mtrk Suite, I began to see a popup error via Mturk Hit Catcher stating I've been logged out. I reloaded my Dashboard and I am still logged in. Why is this happening? Thank you! ## Current Behavior

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by nathan012** [comment]
EDIT: I was able to fix it by reinstalling Mturk Suite. It is now working. Thank you!

**Comment by xspager** [comment]
Hi! I think this was the previous behavior but was broken, if you go to worker.mturk.com or reload a tab it should ask you to login back, after you log in, go to the catcher tab and hit ok, it should keep going again until the MTurk/Amazon log you out automatically after a some hours.

This is much better than not knowing you were logged out I think. To be extra clear, no need to remove the extension. Hope this helps! 😃
