### ISSUE TITLE
HIT Catcher Says "User Logged Out" and Pauses when I'm Logged In (Still)

### ISSUE THREAD

**Issue by steezkelly** [brandonhellman/mturk-suite#141]
I checked around the closed issues and saw another user had a similar issue to mine about a week ago, and I'm still running into the issue. It seems to happen after a couple hours of being up and running (speculation) and I double check the worker website and I'm still logged in. Unfortunately, the hit doesn't get caught and HIT catcher pauses. It seems to occur randomly, with me being able to catch another HIT 10 minutes after the error. The version I'm running is 2.3.11, from September 8th, 2018.

I wish I could describe more, other than this isn't the first time I ran into the issue.  I took a hiatus from MTurk April - August, and just recently came back. Hopefully this helps a bit Kadauchi, thank you for all of your time and effort! We all really appreciate it greatly!

Speculation again: I believe the error occurs only after at least one unique HIT has already been caught.

**Comment by brandonhellman** [comment]
Thanks for filing an issue report. The next time this happens can you open the console log (`Ctrl + Shift + J`) and paste or screenshot the last few red errors.
