### ISSUE TITLE
Feature Request: Create an easy way to unblock a blocked HIT

### ISSUE THREAD

**Issue by TTNebula** [brandonhellman/mturk-suite#143]
Unblock already blocked HITs

Could you please create a way to search the block list, the same way we search history on Tracker? Then create a one click option to unblock HITs already on the block list?

I'd really like to be able to unblock a HIT that I temporarily blocked or blocked by mistake but my blocklist is very long and difficult to search on the finder page.

I use the latest version of Chrome on Windows 10 PC

**Comment by brandonhellman** [comment]
This is a good idea. I don't have a timeline but when I get time I'll add a search or filter for both the block and include lists.
