### ISSUE TITLE
Clear pending earnings older than 45 days?

### ISSUE THREAD

**Issue by oakandsmoke** [brandonhellman/mturk-suite#144]
In the HIT Tracker, the "pending earnings" and "approved waiting payment" sections are only able to update visible days (HITs submitted within the last 45 days). The result of this is that if a user takes a long break or otherwise doesn't use MTS, pending earnings older than 45 days continue to appear indefinitely. Mine, for example, currently says I have 36 HITs pending (in actuality I have 19). It says there are seven approved waiting payment (by my count, there are four).

Is there a way to clear those HITs?  If not, can the tracker be updated to automatically mark outdated HITs as paid, or to at least remove them from the pending totals?

**Comment by brandonhellman** [comment]
This is on the todo for Tracker. Right now the current solution is to export your database then import it. The import function automatically converts all pending HITs to paid.

**Comment by GJSmith3rd** [comment]
I've got the same issue. Will try to export/import. Yep! Works thanks for the tip!
