### ISSUE TITLE
HIT Catcher

### ISSUE THREAD

**Issue by nathan012** [brandonhellman/mturk-suite#147]
HIT Catcher "searched" would run for a couple of seconds and it would stop without warnings. I would then have to manually reload or pause and unpause in order for HIT Catcher to continue searching for my HITs. Why is this happening and how can I fix this? Thanks!
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by bmcg2201** [comment]
I am having the same problem today.  Using google chrome/windows 10.

edit: seems to be working properly now

**Comment by nathan012** [comment]
> I am having the same problem today. Using google chrome/windows 10.
> 
> edit: seems to be working properly now

Glad to know I m not the only one. Working now thanks!

**Comment by brandonhellman** [comment]
I was probably tied to MTurk's 503 issues they were having. That being said, Catcher should be able to recover from that so I'll take a look into it.
