### ISSUE TITLE
Will a High PRE Get Your Account Banned?

### ISSUE THREAD

**Issue by nathan012** [brandonhellman/mturk-suite#148]
Hey guys,
I am just wondering if having a high PRE will be a risk of having your account banned? Does anyone know? Thanks!

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by brandonhellman** [comment]
Page Request Errors (PREs) won't open you up to a suspension/ban.

From the [Acceptable Use Policy](https://www.mturk.com/worker/acceptable-use-policy) the part that would pertain to PREs would be `(3) do not disrupt or impair the operation of the website or the integrity of the marketplace (e.g., scripts and automation tools that call MTurk continuously and at high frequency aren’t OK)`. 

From what I have been gathered, you pretty much have to purposely attack them to reach this.
