### ISSUE TITLE
Hit Catcher Page Jumps around

### ISSUE THREAD

**Issue by djdoubt03** [brandonhellman/mturk-suite#153]
## Expected Behavior
The web page should not jump around

## Current Behavior
Viewing the hit catcher page the blocks jump around

## Steps to Reproduce (for bugs)
Open hit catcher with a few requesters  added

## Your Environment
Windows 10 (October Update)
Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
MTS VER: 2.4.0 Saturday, October 6, 2018

SEE ATTACHED SCREEN SHOT GIF
![hit_catcher_screen_jump_cap](https://user-images.githubusercontent.com/35897227/47035105-2a751700-d147-11e8-9bf6-9a599aa3c9f7.gif)

**Comment by brandonhellman** [comment]
Thanks. I'll try to see if I can track down the issue. Looks like its happening each time the display updates a Watcher's stats.
