### ISSUE TITLE
Run Watchers on HIT Catcher Simultaneously?

### ISSUE THREAD

**Issue by nathan012** [brandonhellman/mturk-suite#154]
Hi there,

Is there a way to search all "Watchers" in HIT Catcher simultaneously or at the same time without having to run search one at a time? That would help a lot and saves time. 

Thanks! 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by brandonhellman** [comment]
Sounds like a good idea to me. No timeline when this will get added at the moment though.

**Comment by nathan012** [comment]
Thanks! Looking forward to it :)

**Comment by KPcanAdmin** [comment]
That would be nice. I just come here to ask the same thing.
