### ISSUE TITLE
How about a way to catch HITS by pay?

### ISSUE THREAD

**Issue by jerseyg1983** [brandonhellman/mturk-suite#159]
I was curious if it would be possible to add a feature to catch HITS (that I am qualified for) by pay rate?  For example, catching all HITS over $3.00 or some such thing.   Obviously,  there would need to be a limiter or some such control, but I realized even with the catcher feature, how much I am missing out on. Maybe I am crazy...😁 Just a thought!

**Comment by brandonhellman** [comment]
Thanks for the feature request but MTS will never have an auto accept function such as this.
