### ISSUE TITLE
Hit Finder exporter - add text option

### ISSUE THREAD

**Issue by Leviathon2** [brandonhellman/mturk-suite#16]
It would be beneficial to allow text to be added when exporting a hit. I usually like to include the information from the mturk hourly script before posting, as some people don't update the posts and will miss it if I edit the forum post after posting the hit.

**Comment by brandonhellman** [comment]
Thanks for reminding me to add this back in.

**Comment by brandonhellman** [comment]
https://github.com/Kadauchi/mturk-suite/projects/3#card-7019496

**Comment by Leviathon2** [comment]
Any eta updates?

**Comment by brandonhellman** [comment]
Coming in v2.3.0
