### ISSUE TITLE
Block Location does not recognize US states

### ISSUE THREAD

**Issue by Pascal666** [brandonhellman/mturk-suite#161]
When the "Block Location" option is checked, and a qualification for a HIT is "Location is US", a location of US-<2 letter state abbreviation> e.g. US-NY, is qualified to take the HIT, but MTS blocks it anyway.

Is it possible for MTS to use MTurk's assessment of whether my location qualifies for the HIT, instead of trying to parse all the values itself?

**Comment by ghost** [comment]
This is a pretty big flaw, not sure why it hasn't been noticed or fixed since Nov. All the "Block Location" option does for me is basically block all HITs that use "Location is:" or "Location is NOT:" as a qualifier, whether I qualify or not.

**Comment by ghost** [comment]
Gee, thanks bot.

**Comment by brandonhellman** [comment]
This will be fixed in v3.
