### ISSUE TITLE
I cannot export a hit plain from my queue. Unable to share. 

### ISSUE THREAD

**Issue by KPcanAdmin** [brandonhellman/mturk-suite#164]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:   hp touch screen Windows 10 chrome
* Operating System and version (desktop or mobile):

**Comment by KPcanAdmin** [comment]
I can share from hit finder but not an existing hit inside my queue. I have tried using the arrow to share the hit and nothing is copied to my clipboard. I also tried to use the export box and short is not supported yet. Plain and BB Code doesn't copy anything. Only Markdown works but I am hoping to use plain.

**Comment by brandonhellman** [comment]
Thanks for the report. Its easy enough to replicate. I'll get to this when I have some free time.

**Comment by KPcanAdmin** [comment]
Thank you very much! There is no rush.
