### ISSUE TITLE
Workspace Expander not expanding

### ISSUE THREAD

**Issue by leftfield72** [brandonhellman/mturk-suite#166]
Works fine in Firefox but does not appear to work in chrome Version 70.0.3538.102 (Official Build) (64-bit) or Vivaldi for me.

**Comment by brandonhellman** [comment]
Thanks for the report. The next version 2.4.3 should fix it. Let me know if you're still having issue then.

**Comment by leftfield72** [comment]
Works as expected now.  Thanks for the quick fix :+1:
