### ISSUE TITLE
Requester's qualifications not met while "I'm qualified to work on" checked

### ISSUE THREAD

**Issue by ghost** [brandonhellman/mturk-suite#167]
## Expected Behavior

Expecting to not catch HITs I'm not qualified to work on

## Current Behavior

Catches HITs I'm not qualified to work on

## Steps to Reproduce (for bugs)

1. No idea, happened to occur for 2 separate HITs today for the first time ever. Didn't see anything the same about them except this.
2.
3.
4.

## Your Environment

* Version used: 2.4.2
* Browser Name and version: Firefox 63.0
* Operating System and version (desktop or mobile): Linux Mint 18.3 Dell Inspiron Laptop

![boxchecked](https://user-images.githubusercontent.com/8769067/48864876-f28f6e00-ed9b-11e8-813d-94aac74a2343.png)
![specifiedquals](https://user-images.githubusercontent.com/8769067/48864877-f28f6e00-ed9b-11e8-9446-50f3d504f20e.png)

**Comment by brandonhellman** [comment]
Do you recall which requester posted the HITs you aren't able to accept?

**Comment by ghost** [comment]
> Do you recall which requester posted the HITs you aren't able to accept?

Sorry, no. But it happened twice from 2 different requesters. This leads me to believe it may happen again, in which case I can take note. Will post back here if/when that occurs. Again, my apologies for not having the forethought to get that for you.

**Comment by brandonhellman** [comment]
Totally fine. I'm asking because its possible it could be a block, though 2 different requesters lower that chance. It'll appear that you're qualified for the HIT up until you actually try to accept it, so HIT Finder an MTurk can't tell you're blocked so they will slip through `Only Qualified` being checked on both.

**Comment by ghost** [comment]
Haven't seen any more of this. Guessing it was a transient thing, maybe even on Amazon's side, especially since I hadn't seen it at all until that one day- then it happening twice in the same 5 minutes.

I don't know if I close this, whether it can be reopened should the behavior resurface. So I'll just leave it as-is to be handled as whoever else sees fit.

**Comment by brandonhellman** [comment]
I'll go ahead and close this then. You are able to reopen issues so if it pops back up you can update in here.
