### ISSUE TITLE
Workspace Expander causes the submit button to be partially hidden.

### ISSUE THREAD

**Issue by cattcali** [brandonhellman/mturk-suite#168]
After the latest update, with Workspace Expander on, the copyright section of the HIT page is moved up above the "Report this HIT" section, causing it to cover the majority of the submit button.  This happens about 99% of the time and the other 1% of the time, the copyright section will be below the submit button and partly on top of the "Report this HIT" section.

The is what it's supposed to look like:
![screenshot 17](https://user-images.githubusercontent.com/35941200/48927169-d0bfe500-ee88-11e8-89b0-da4863f92961.png)
 
This is what it looks like with Workspace Expander on:
![screenshot 18](https://user-images.githubusercontent.com/35941200/48927189-e7fed280-ee88-11e8-9358-2cba2e71188a.png)

I'm using the most up to date Firefox.

**Comment by Danebow** [comment]
I have this same issue, and it's doing the same thing basically with Chrome, and they said it was fixed... but it is not. Any ideas?

**Comment by Danebow** [comment]
Sorry, but you have an even worse, but similar issue on Chrome. Let me know when that is taken care of too. Can get screenshots/etc if necessary.

**Comment by brandonhellman** [comment]
Just pushed a fix so whenever you get updated to `2.4.4` and if it is still happening let me know.
