### ISSUE TITLE
Mturk SuiteV2.4.4 problem ( accepted HIT is blank )

### ISSUE THREAD

**Issue by madhanprashanna** [brandonhellman/mturk-suite#169]
after update the mturk suite

v.2.4.4 

accepted HIT are all go blank 
all HITs are blank
but accepted and time running
after disable MTS HIT open normal

 please repair soon please

**Comment by brandonhellman** [comment]
Disable workspace expander

**Comment by madhanprashanna** [comment]
thanks bro 
 i figured it out and thanks for fast response and update
