### ISSUE TITLE
Projected earnings for the week in HIT Tracker is inconsistent

### ISSUE THREAD

**Issue by cattcali** [brandonhellman/mturk-suite#17]
I have been noticing that the projected earnings for the week isn't always correct.

For example; on Friday morning, it showed my projected earnings as ~$110 with 702 HITs completed.  A couple of hours later, after refreshing the page, it said my earnings were ~$108 with 697 HITs completed.  I went to my dashboard and counted, and I had 734 HITs completed.  I didn't have any rejections.  I synced for the last 45 days and it didn't change.

Yesterday(Sunday), it was counting the HITs I did that day as the only HITs for the week.  Right now, it is only counting the HITs I completed today(Monday) and not the ones I completed yesterday(Sunday).

I have a feeling that sometimes it counts Sunday as the first day of the week and sometimes it counts Monday as the first day of the week, which is causing the discrepancy. 

I am using v2.1.7
Chrome Version 64.0.3282.119 (Official Build) beta (64-bit)
Windows 10 Home 64-bit

**Comment by brandonhellman** [comment]
You are absolutely right. At some point later in the day, it miscalculates converting local time to PST (even while in PST) which does make it think Monday is the start of the week.

**Comment by brandonhellman** [comment]
https://github.com/Kadauchi/mturk-suite/projects/4#card-7039772

**Comment by cattcali** [comment]
That's good to know.  At one point I thought I was going crazy lol.  Thanks for the update.

**Comment by cinereous** [comment]
Time, what is time?
