### ISSUE TITLE
Breaks Panda Crazy 

### ISSUE THREAD

**Issue by friendlyturker** [brandonhellman/mturk-suite#173]
I much prefer Panda Crazy to Hit Catcher because it offers a lot more panda features such as the ability to panda requesters or hits that are no longer available but MTS stops this function from working. I have to disable MTS to use panda crazy the way I would like to which doesn't make sense because if MTS can't panda in that way, it shouldn't be interfering with a script that can. If I have to choose I'll choose panda crazy hands down.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by brandonhellman** [comment]
MTS shouldn't be interfering at all with Panda Crazy. A lot of people use the HIT Finder + Panda Crazy combo with MTS for the rest. Can you pop open the console `ctrl+shift+j` on a page that MTS is break Panda Crazy and relay the error/

**Comment by friendlyturker** [comment]
I don’t know what this means.

**Comment by friendlyturker** [comment]
unavailable hits with MTS downloaded and enabled

![mts panda 1](https://user-images.githubusercontent.com/46328749/50618000-0f9c7e00-0ebe-11e9-831e-b00769afdb5d.png)

**Comment by friendlyturker** [comment]
unavailable hits with mts disabled

![mts panda 2](https://user-images.githubusercontent.com/46328749/50618021-2e027980-0ebe-11e9-8008-5a9746d4b5ff.png)

**Comment by SlidingHorn** [comment]
I have this same issue....I have no idea how to troubleshoot or fix it :(
