### ISSUE TITLE
Turkopticon Doesn't Load

### ISSUE THREAD

**Issue by friendlyturker** [brandonhellman/mturk-suite#174]
When on the Hits page and the color-coded icon appears, if you click it to go to Turkopticon, it goes to the page to leave a review. 9/10 if I am clicking that, I am doing so to read the reviews and see why it is that color, not leave my own review for a hit I have not even completed yet. However, when clicking TO from Hit finder, it goes to the correct page.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by brandonhellman** [comment]
Are you clicking the yellow link labeled `Turkopticon` or the blueish link `Review on TO`?

**Comment by friendlyturker** [comment]
I’m clicking the colored icon that’s either red yellow green or grey that
gives 3 review websites to choose from.

**Comment by friendlyturker** [comment]
What logos im referring to

![mts logos 2](https://user-images.githubusercontent.com/46328749/50617377-e5958c80-0eba-11e9-8c44-37fe09802435.png)

**Comment by friendlyturker** [comment]
When clicking this logo then TO, goes to make a new review instead of to the requester's TO reviews,
![mts logos](https://user-images.githubusercontent.com/46328749/50617386-f47c3f00-0eba-11e9-88c6-a3442919f2f9.png)

**Comment by friendlyturker** [comment]
When clicking TO directly from Hit Finder it does what I would like for it to do.

![mts logos 3](https://user-images.githubusercontent.com/46328749/50617400-137ad100-0ebb-11e9-9111-8e9c1a69aa90.png)
