### ISSUE TITLE
MTurk daily activity page is missing links to review sites

### ISSUE THREAD

**Issue by kimadagem** [brandonhellman/mturk-suite#178]
Up until today I was using the link there to post reviews on TO2. It didn't completely autofill - I still had to insert the hit title and pay - but that wasn't hard, I just pasted from my own database. Today the review site links are missing from that page. I was able to use the link on the MTurk Hits page, but only because I hadn't refreshed it; if I had that hit might have been gone.

**Comment by brandonhellman** [comment]
This one should be fixed.
