### ISSUE TITLE
Time on logged hits is changing randomly

### ISSUE THREAD

**Issue by Leviathon2** [brandonhellman/mturk-suite#18]
Using latest version of Chrome.

Speed is at 3000 ms. For some reason, logged hit time are changing to the latest found hit. For example, I had hits that were logged at 6:00 and a couple minutes later, the times suddenly changed to 6:04. So, I have a bunch of logged hits between 6:03-6:05.

**Comment by brandonhellman** [comment]
Documented in there wiki [here](https://github.com/Kadauchi/mturk-suite/wiki/HIT-Finder#columns)

I bounce between wanting to display most recent seen time and first seen time since both have their uses.
