### ISSUE TITLE
New update has ruined Slate theme

### ISSUE THREAD

**Issue by MartinStell** [brandonhellman/mturk-suite#180]
The rows are now black with white text in Hit Finder. The other rows remain the proper color with blue text.

If only TO is selected, there are no colors. Colors seem entirely based on TV.

https://i.imgur.com/rl4TqEi.jpg

**Comment by brandonhellman** [comment]
Right now the row colors are only based off of TO, but it looks like its not coloring at all for no TO ratings which is why you're getting the black with white text. Thanks for the issue report.
