### ISSUE TITLE
A way to disable TO2

### ISSUE THREAD

**Issue by concreteclam** [brandonhellman/mturk-suite#183]
Hey Kadauchi! Thanks for all of your work on MTS, it's appreciated. A quick thing - on the latest build of MTS, I can't selectively disable TO2 anymore. I don't like using TO2 as it messes with the review "colors", as there usually isn't any (or very poor) data for it to pull from. It would be awesome if I could still disable this in a future release.

**Comment by brandonhellman** [comment]
Sure that's not a problem. It will probably come in the form of a setting to control the colors instead of flat out disabling TO2 (you'll see the data but it won't affect colors) when I add this back in.

**Comment by concreteclam** [comment]
Awesome, thanks a lot!
