### ISSUE TITLE
Since 2/5, if "There are no more," all hits now missing the yellow Hit Catcher buttons for "Once" and "Panda" Was previously fixed in 5/2018.

### ISSUE THREAD

**Issue by Octopod2** [brandonhellman/mturk-suite#185]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by brandonhellman** [comment]
I just tested and they still appear to be showing up. Do you have HIT catcher open before opening the links?

**Comment by Gozergoz** [comment]
I'm having the same issue.  I have the catcher open, but the once and panda buttons don't appear.  I re-installed the mturk suite just in case, and it still doesn't work.

**Comment by Octopod2** [comment]
Now I'm getting buttons on only some of the hits. I believe it was caused by one of the updates last week.
