### ISSUE TITLE
Hit Catcher Not catching HITS since Feb 5th 2019 update..Watcher setting information missing

### ISSUE THREAD

**Issue by lrnvk** [brandonhellman/mturk-suite#186]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by brandonhellman** [comment]
Can you open the console (`Ctrl+Shift+J`) and see if there are any error in there? I just ran a few HITs through Catcher and everything appears to be working fine on my end.

**Comment by lrnvk** [comment]
Yes I see a bunch of errors when I open the console

**Comment by lrnvk** [comment]
It was working fine yesterday before the "update"

**Comment by lrnvk** [comment]
Here are just a few of the "error" messages I see:
Error: Could not establish connection. Receiving end does not exist.
Error: Invalid tab ID: 222
Error: WebExtension context not found!

**Comment by brandonhellman** [comment]
I always forget if reinstalling deletes your data so backup anything that needs to be backed up (tracker database, include/block lists) and reinstall the extension.

**Comment by lrnvk** [comment]
I didn't do anything different from yesterday. I am sorry I am not really tech savvy so I am not sure what You are saying to do.

**Comment by lrnvk** [comment]
My block list/ include list looks fine, nothing has changed. What need to be done to fix my "Hit Catcher"??

**Comment by lrnvk** [comment]
By the way I am on a Mac and I use firefox browser which I have used the entire time I have had MTurk suite and had no problems.

**Comment by brandonhellman** [comment]
I'm asking you to export your block/include list and HIT Tracker database if you use that. Then uninstall and reinstall MTS. The exporting is so you don't lose this data.

Sometimes MTS seems to just randomly break for no reason and a reinstall like above is the quickest way to fix it. The errors you're having aren't something I have the time to address head on right now so it'll be easier and quicker to just reinstall.

**Comment by lrnvk** [comment]
Ok thank you! I am just nervous if I uninstall and reinstall in case something messes up..lol
Thank you for getting back to me so quickly and for all that you do. 
Much appreciated

**Comment by bgollmer** [comment]
> I always forget if reinstalling deletes your data so backup anything that needs to be backed up (tracker database, include/block lists) and reinstall the extension.

Can you provide steps on how to backup?  I particularly want to copy hit catchers to a new computer.
