### ISSUE TITLE
Time display is not proper for Hits :

### ISSUE THREAD

**Issue by sujithmturk** [brandonhellman/mturk-suite#19]
I just like to bring to your notice that , there is regular update of script.  I am very happy about it. But Ilike to tell one small suggestion that as you have changed the time format for hits... It is found very difficult to find hits based in time. Because top hit shows time as 1:30 but below hits shows time as 2:00 which leads to confusion and very difficult to search for hits all time. So I kindly request you to make us show hits based on time as it was before which could be easy for all to see hits posted on time and we can avoid searching for it by scrolling the screen always.. If the time shown is in format like 1:00,1:01, 1:02.... it would be easy instead of 12:30, 11:30,1:00 irregular display of time in MTS finder screen. Please make this change as it could be helpful for all working on mturk. Once again I thank for giving a wonderful script for making our work easy.

**Comment by brandonhellman** [comment]
Duplicate #18
