### ISSUE TITLE
Blocklist question

### ISSUE THREAD

**Issue by kimadagem** [brandonhellman/mturk-suite#191]
This is not an issue, just a question, but I can't find anyplace else to ask it. If there is another place, please let me know.

My question is: If a requester changes their name will the blocklist catch it? I did an export and see that the format includes both name and ID, but they seem to be together in one record, so I'm wondering what will happen if the requester changes their name.

I can offer an explanation but it might be long and I don't think it matters for coding purposes. If it would help you let me know and I'll add it.

Also - I see that there's a way to manually add a requester without their being on a list of hits somewhere. Thank you for doing that. Usually I add from the list but sometimes I pull from my own hit database, so this is good to have.

**Comment by brandonhellman** [comment]
Questions here work.

If the `requester id` is the `match` field then as long as they don't create a new requester account then it will still block them. The `name` field is used so you know what it is blocking instead of just a random string starting with A.
