### ISSUE TITLE
Question about using non-strict matching for blocklist

### ISSUE THREAD

**Issue by kimadagem** [brandonhellman/mturk-suite#192]
For a hit with a long title, like this one:

"New Three-D Orientation Memory Game: The object 3D orientation Game (Bonus up to $1.50) [fast]"

If I unclick "strict matching" what will happen?

There are multiple versions of this hit posted and I can't access any of them. I've messaged the requester so I don't really want to block him, but these are cluttering up the list and it takes time to block them all individually - especially when new ones keep showing up. I'm guessing your system doesn't allow wildcards so I'm thinking removing strict matching might work.

Thank you.

**Comment by brandonhellman** [comment]
Non-strict match will just check to see if the `match` is in the requester name/id, group id or title. A non-strict match using `New Three-D Orientation Memory Game` would block that HIT since that string is found in the title.
