### ISSUE TITLE
Hit Catcher rarely alerts me that a hit has been caught.  I have the latest Chrome.  Will settle for any kind of alert.

### ISSUE THREAD

**Issue by Octopod2** [brandonhellman/mturk-suite#20]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by brandonhellman** [comment]
The sound alerts from HIT Finder will be making their way to HIT Catcher to offer an alternative to text-to-speech.
