### ISSUE TITLE
Hit Catcher broken in latest update 2.6.6 Mturk Suite(Chrome)

### ISSUE THREAD

**Issue by LajamerrMittesdine** [brandonhellman/mturk-suite#206]
## Expected Behavior

Add a HIT to the HIT Catcher.

## Current Behavior

When I try and add a HIT it does nothing in the HIT Catcher.

## Steps to Reproduce (for bugs)

1. Open HIT catcher
2. Click add watcher
3. Type in the URL of the HIT or copy-paste.
4. Click OK

Nothing happens. Nothing is added

## Context

Trying to use the hit catcher and no longer works.

## Your Environment

* Version used: 2.6.6
* Browser Name and version: Chrome Version 72.0.3626.119 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Fedora 29

**Comment by mrzoink** [comment]
I get the same thing when I try to catch the Computer Vision HITs. The other HITs I've tried have worked fine.

It automatically removed my existing PANDA catcher for the Computer Vision HIT in Hit Catcher when I applied the update, and left all the rest as is.

I've tested since then, and it's added every HIT I've tried so far except that one.

**Comment by LajamerrMittesdine** [comment]
> I get the same thing when I try to catch the Computer Vision HITs. The other HITs I've tried have worked fine.
> 
> It automatically removed my existing PANDA catcher for the Computer Vision HIT in Hit Catcher when I applied the update, and left all the rest as is.
> 
> I've tested since then, and it's added every HIT I've tried so far except that one.

Yeah I've only been trying this on Computer Vision HITs. Weird that this one is broken and others are fine.

**Comment by brandonhellman** [comment]
Catcher shouldn't have been affected at all since no files that it relies on changed in the last update. Does restarting the browser fix anything? If not can you pop open the console (`ctrl+shift+j`) and see if there are any errors (ignoring any that are "Failed to load resource:").

**Comment by mrzoink** [comment]
Restarting Chrome didn't help, and neither did a full reboot (Chrome OS.)

I'm not sure how to see the errors, but this is visible in the bottom pane of the console:

`https://worker.mturk.com/projects/3V6FYJLHFQOMYAQQ4EXE8CMV74B05C/tasks/32TMVRKDGN3LFGSI38H8LG1XI3Z84T?assignment_id=3NVC2EB65R5HYAYP60FLZ8SAL73Y3D&auto_accept=true`

I have no catchers currently running, at least nothing is visible in the HIT Catcher window.

**Comment by mrzoink** [comment]
Oops. Now this one is visible too:

[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: chrome-extension://iglbakfobmoijpbigmlfklckogbefnlf/bootstrap/fonts/glyphicons-halflings-regular.woff2

Edit: And the other one went away.

Sorry if this isn't helpful.

**Comment by LajamerrMittesdine** [comment]
> Catcher shouldn't have been affected at all since no files that it relies on changed in the last update. Does restarting the browser fix anything? If not can you pop open the console (`ctrl+shift+j`) and see if there are any errors (ignoring any that are "Failed to load resource:").

I had to reset my browser for the issue to fix itself. Everythings working fine now. Thank you very much.
