### ISSUE TITLE
MTS not keeping track of earnings

### ISSUE THREAD

**Issue by LaDeDaa** [brandonhellman/mturk-suite#207]
Was working fine yesterday and for part of today, but then it stopped tracking my submitted hits altogether.

**Comment by brandonhellman** [comment]
Can you try restarting the browser and then going into Tracker and doing a 45 day sync. If that doesn't fix anything can you pop open the console (ctrl+shift+j) and see if there are any errors (on any page that would show the earnings).

**Comment by LaDeDaa** [comment]
Figured it out! It was another issue, not MTS. Sorry about that.
