### ISSUE TITLE
Daily Overview Issue

### ISSUE THREAD

**Issue by ddrtn365WW** [brandonhellman/mturk-suite#21]
I had some hits missing because I did not do a hit database backup for a few days in 2016 and a few months in 2017.  I managed to import them in by adding the proper format into a backup and re importing.

example:{"assignment_id":null,"date":"20170426","hit_id":"3E9ZFLPWOY3BKQYVF53PER5J0P4XI1","requester_feedback":null,"requester_id":"ATED2DLBTD3Y1","requester_name":"Insight Collector","reward":{"amount_in_dollars":0.40,"currency_code":null},"state":"Paid","title":"Daily Decision Making (Extra Bonuses Inside)"},

I had my brackets correct at the end as well.

If I click on daily overview, the items I imported are not showing up.  I see it just fine if I search the tracker for the text involved or put a date in the search field - any appropriate date (even ending 01-31-2018).  It may be my problem alone, but there may be others who reconstructed missing hits as well.
Please don't waste a lot of time, as it works well enough for me.  But if it is an easy fix, that would be great.

I imagine you can reproduce this by adding my entry above into one of your imports and seeing that it won't show in the daily overview, but works as expected otherwise. 

I am using the latest chrome and windows 10 on a desktop computer.  

Also, when returning hits, they are registering as abandoned pretty often I have 37 Abandoned and 33 returned.  I keep records, and the abandoned were returned.  (I did not check every one, but I am very sure I am returning them.)  I remember a couple timing out on me, so they were abandoned.

I figured that was a glitch, so I stopped panicking, but I thought I would let you know.

I so appreciate your extension. I have some suggestions, but would rather mention them privately.

Thank You

**Comment by brandonhellman** [comment]
I'll check the daily overview stuff.

The tracking of returning/abandon is kind of hacky and I'm probably going to be just combining them into something like "X did not dos" instead.

If you want to mention them privately, I am available on reddit, turkerhub and mturkcrowd (same username) if you want to drop me a message there.

**Comment by ddrtn365WW** [comment]
Thank You.  I am registered at turkerhub but I get this when trying to see your profile.
TurkerHub mTurk Forum | Scripts, HITs, & mTurk Community - Error
This member limits who may view their full profile.  I was just going to ask if the add to hit catcher link (once) could be in the search results.  It seems to just add an extra step to click accept first.  I understand if this is too much trouble, or bloats the script.  Thank you for all of your effort, it is appreciated.

**Comment by brandonhellman** [comment]
Solid suggestion. I know my project board is woefully incomplete so there is no way for anyone to know all the plans right no but this is something that will be changing.

You should be able to click my (or anyones) avatar on TurkerHub and then there should be a message link somewhere, or you can go [here](https://turkerhub.com/conversations/add) and manually add participants.

**Comment by ddrtn365WW** [comment]
I thought that was a public post, not private.  Thanks for letting me know.  I hate to ask for too much, you have to be very busy.
