### ISSUE TITLE
Tracker not syncing properly

### ISSUE THREAD

**Issue by TurkEmup** [brandonhellman/mturk-suite#210]
For a few days the tracker hasn't been syncing properly. It shows that it has synced, but the information is incorrect. Usually I sync both the last 45 days and today, depending. It's showing my pending hits number in the several hundreds, and that I have over $100 bucks pending.  I know this isn't the case, as I've only done 100 or so hits the last few days and my Mturk dashboard isn't showing the same information.  Is there an easy fix, or is this a bug?

**Comment by brandonhellman** [comment]
Export your database then import that file. It should fix any discrepancies that you are having between the dashboard and Tracker.

**Comment by TurkEmup** [comment]
Thank you! That fixed it. :)
