### ISSUE TITLE
No Alert voice from HIT Catcher anymore

### ISSUE THREAD

**Issue by ghost** [brandonhellman/mturk-suite#212]
## Steps to Reproduce (for bugs)

1. Set Hit Finder settings for 'Sound 4' for it & 'Voice' for Catcher
2. Am able to hear 'Sound 4' when HITs are caught in Finder
3. HITs appear in queue silently
4.

## Your Environment

* Version used: 2.6.6
* Browser Name and version: Firefox 65.0.1
* Operating System and version (desktop or mobile): Linux Mint 18.3

**Comment by ghost** [comment]
Same issue after upgrading to 2.6.7.
Doesn't matter which I choose from the Alert Drop-Down menu. Voice or sound no change.
Also no help if I disable the Tampermonkey Extension.

**Comment by ghost** [comment]
Still a problem in MTS 2.6.8 with Firefox 66.0.

**Comment by toutils** [comment]
I just got this working on linux in chromium at least. Chromium requires espeak and speech-dispatcher installed on the system, and then starting with a flag --enable-speech-dispatcher. I believe firefox requires the same thing (obviously not the chromium flag). I don't use firefox much anymore but I can at least confirm this works in chromium on linux with some system tweaking, it doesn't out of the box but it doesn't seem to be an MTS problem.

**Comment by ghost** [comment]
> requires espeak and speech-dispatcher installed on the system, and then starting with a flag --enable-speech-dispatcher.

I don't understand why if the speech-related packages resolve the lack of voice alerts, why the other sound alerts would also fail. eg. Include Match Sound: Sound 1 through Sound 6

**Comment by ghost** [comment]
FWIW, still a problem in MTS 2.6.9 with Firefox 66.0.2 on Linux Mint 18.3 (Ubuntu 16.04).

**Comment by likefrieswiththat** [comment]
Running Chromium also and having the same issues on a new pi3+ I setup just for turkin mostly. tried espeak and speech-dispatcher with no luck.
