### ISSUE TITLE
No red, green, or yellow on turkopticon ratings today, only gray.

### ISSUE THREAD

**Issue by Scottyc2112** [brandonhellman/mturk-suite#219]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by SlidingHorn** [comment]
This is most likely an issue with the TO API being slow to respond/not responding at all.  Can you post a console screenshot?  (Ctrl+Shift+J)

*EDIT:  A copy/paste in code tags would probably be more useful than a screenshot, I guess*

**Comment by toutils** [comment]
I haven't been able to get MTS to display TO data, either on TO1 or TO2 for months. I just switched setups and thought I'd try to get the latest version of MTS going today to see if it's been fixed, and I have the same problem. 

I always have to revert to an earlier commit, I've been using
42410e0b529d9a45de2317568363e585f0b09cba
Using this the TO data shows immediately, so it doesn't seem to be TO's problem. 

To be more specific I switched to this commit immediately after trying to get the current release on chrome, which shows as 2.6.8. 
2.6.8 - Doesn't show TO data. 
2.4.5 - Shows TO data. 

I haven't tested much in between. When I have time I'll see if I can find the version where TO stops working and hopefully try to get this solved.

**Comment by toutils** [comment]
I'm pretty sure I've found the problem. 
https://github.com/Kadauchi/mturk-suite/blob/7f1f350b4a4129d90241c8727a3e3b139a635ae4/background/reviews.js#L225

https://github.com/Kadauchi/mturk-suite/commit/e723bf46e3235cad9aeb19c6c8862b27233355a2

Both TO1 and TO2 are disabled by this line. 

TO2 is throwing net::ERR_CERT_COMMON_NAME_INVALID and chromium at least will refuse to fetch it, I can see why it's disabled. Playing with it there's two ways to easily fix it. 

1: Uncomment the line: this will continue to send requests to TO2 which will fail, but it won't otherwise hold up anything. TO2 is also disabled elsewhere in the file, and even if you re-enable it ( I did playing around it ), everything was fine except for TO2 being constantly hit and requests failing. 

2: Add this in place of the commented out line (directly underneath)
``await updateCache(`turkopticon`);``
This will re-enable TO while keeping TO2 disabled. 

I'm not going to submit a pull request for a single line but TO is completely disabled until this get's fixed.

**Comment by Scottyc2112** [comment]
![image](https://user-images.githubusercontent.com/48563490/55004579-e0734580-4fb0-11e9-87e6-2c69bc7a52c8.png)

**Comment by Scottyc2112** [comment]
Toutils how do i use that?

**Comment by Scottyc2112** [comment]
i don't understand how to fix all that...i don't even know where to look....I'm not a programming expert.....and i'm wasting work time dealing with this and it's not the first time.

**Comment by Scottyc2112** [comment]
how do i switch to 2.4.5?

**Comment by toutils** [comment]
Switching to 2.4.5 is probably overkill now, but either way the steps are basically the same except for adding this fix in the current version. 

1) Download the extension from github
- For the current version, go to the front page, https://github.com/Kadauchi/mturk-suite, click the green "Clone or download" button, and download the zip. 
- For 2.4.5 do the same thing, only go here https://github.com/Kadauchi/mturk-suite/tree/42410e0b529d9a45de2317568363e585f0b09cba
2) Extract the zip somewhere your not likely to delete. If you delete it the extension will still be there but upgrading will be a million times more of a pain. (You need to know where you put it originally to reload the extension for an upgrade). 
3) If it's the master / current version and you want to apply this fix, go to the folder you extracted the extension into, go into the background folder, open reviews.js and find line 225. 
You can just search for `await Promise.all([updateCache`
Add ``await updateCache(`turkopticon`);`` 
underneath 
``//await Promise.all([updateCache(`turkopticon`), updateCache(`turkopticon2`)]);``. 
4) Install the unpacked extension into chromium
- Go to the extensions page in chromium from the menu or open a tab and go to `chrome://extensions/`
- Enable developer mode in the top right of the page
- Click "Load unpacked" and select the folder you extracted the extension into
That's it, it should be loaded now. These instructions are pretty much the same as the front page except for modifying reviews.js to add the fix. 
It might seem complicated but it isn't, after you've done this a couple of times it's nothing.

**Comment by toutils** [comment]
I should also note that if you load an extension like this chrome won't auto-update it (which might be a good thing depending on your preference). You have to update it manually yourself by replacing the content of the folder you loaded on the extensions page with the new version, and then on the extensions page clicking the circle arrow to reload the folder.
**If you try to upgrade by removing the extension and adding it again, ie the instructions above, it will delete your hit database**.
Again it's not complicated once you familiarize yourself with it. You should export your hit database occasionally anyway, every 30 days or so before your hit history drops off the mturk dashboard and you can't update to get it back.

**Comment by Scottyc2112** [comment]
I might try it when iv'e got time but feel like i shouldn't have to do all that......still not sure i can even do what you're talking about.....I'll just use TO as is for now. I have to actually look at the reviews more often now since there is no green or red but so be it.
    On Monday, March 25, 2019, 8:27:41 PM EDT, toutils <notifications@github.com> wrote:  
 
 
I'm pretty sure I've found the problem.
https://github.com/Kadauchi/mturk-suite/blob/7f1f350b4a4129d90241c8727a3e3b139a635ae4/background/reviews.js#L225

e723bf4

Both TO1 and TO2 are disabled by this line.

TO2 is throwing net::ERR_CERT_COMMON_NAME_INVALID and chromium at least will refuse to fetch it, I can see why it's disabled. Playing with it there's two ways to easily fix it.

1: Uncomment the line: this will continue to send requests to TO2 which will fail, but it won't otherwise hold up anything. TO2 is also disabled elsewhere in the file, and even if you re-enable it ( I did playing around it ), everything was fine except for TO2 being constantly hit and requests failing.

2: Add this in place of the commented out line (directly underneath)
await updateCache(`turkopticon`);
This will re-enable TO while keeping TO2 disabled.

I'm not going to submit a pull request for a single line but TO is completely disabled until this get's fixed.

**Comment by Scottyc2112** [comment]
I appreciate your help.....Still not sure how to do all that and i shouldn't have to.....at this time i'm just going to use TO as is....I'll have to look at more reviews since there are no green and red icons but so be it.

**Comment by Scottyc2112** [comment]
i tried to do those things you were talking about, haven't been able to.......When will they fix it????

**Comment by Scottyc2112** [comment]
I found js in the zip but couldn't seem to open it to reveal the lines of code.

**Comment by toutils** [comment]
Make sure you extract the zip, don't just open it in explorer on windows, and then you can open the js file in notepad.

**Comment by brandonhellman** [comment]
Should be fixed in v2.6.9.
