### ISSUE TITLE
Nearly 100% utilization all of a sudden in Chrome

### ISSUE THREAD

**Issue by AlienGit** [brandonhellman/mturk-suite#22]
You haven't made an update, Chrome hasn't had an update, but suddenly my laptop CPU is cooking hard. 93-97% utilization. Any ideas what to look for? I'm not doing anything unique from normal.

**Comment by brandonhellman** [comment]
Is it still doing it or did this resolve itself?

**Comment by AlienGit** [comment]
It resolved, but through no intervention (not even a reboot). Wasn't sure whether to leave it open or leave it in case it happens to someone else.

**Comment by brandonhellman** [comment]
I'll close it, it was probably a random oddity (hopefully).
