### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by ddrtn365WW** [brandonhellman/mturk-suite#224]
## Expected Behavior

It would be really great if you could delete hits and requesters separately from the blocklist.  Hits have to be removed due to reuse by multiple requesters, or many various reasons. BUT requesters pretty much remain on the blacklist.  Even if they could be exported individually (and reimported individually,) that would help so much.  Or if the hit could be associated with a hit id, so it would never be the same title with a different requester.  I know you work hard on this, so sorry to be such a bother.  Thanks for listening.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by brandonhellman** [comment]
You can block with group id now.
https://github.com/Kadauchi/mturk-suite/wiki/HIT-Finder#addedit-block-list-item

**Comment by ddrtn365WW** [comment]
I am so sorry.  I will read all of that stuff (it was right there, so no good excuse).  The reason I thought this is because sometimes there is a green checkmark indicating I have done the hit.  BUT there is not a check mark indicating I have worked for the requester.  I just assumed it was because of a duplicate title but a different requester.

I would still love to purge the list but not the blocked requesters, just because the list gets unruly.  I tried to find this in chrome's local data files, but could not find a place to edit there.  If there is a trick I could try, that would be great.  Again, I am sorry I assumed incorrectly.  Thank you for MTS, it is great.

**Comment by brandonhellman** [comment]
A green checkmark next to a HIT title and not the requester name would indicate that you've done a HIT for a different requester, so you assume right on that.

You could delete them all at once with the `Delete All` button at the bottom of the block list popup.

The code below will remove any block that is not a requester id or group id in case you want to just remove those. To use this code open up the MTS options, press F12 to open the console and then paste the code in there and hit enter.

```
chrome.storage.local.get([`blockList`], ({ blockList }) => {
	Object.values(blockList).forEach(({ match }) => {
		if (!match.startsWith(`3`) && !match.startsWith(`A`)) {
			delete blockList[match];
        }
	});
	
	chrome.storage.local.set({ blockList });
});

**Comment by ddrtn365WW** [comment]
That is so cool!  I will start doing that.  I have been starting over and deleting all.  This will be so much better.  
 
Thank you for taking the time to help!

**Comment by ddrtn365WW** [comment]
When did you start putting check marks on MTurk pages.  You don't have to answer. But THANK YOU. THIS IS GREAT!
________________________________
