### ISSUE TITLE
hit catcher stops every now and then and rarely catches. please help and advice.

### ISSUE THREAD

**Issue by dn14** [brandonhellman/mturk-suite#227]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by dn14** [comment]
I am using mturk suit for a year.it worked fine and was really helpful. but it is not working since last month. I love this extension as it is like the last hope for international workers on mturk. please help. I have uninstalled and reinstalled it many times. but doesn't work.

**Comment by brandonhellman** [comment]
When it gets stuck again, can you open the console log (`ctrl + shift + j`) and paste the last few errors (or screenshot).

There will be a bunch of 422 (Unprocessable Entity) errors, those are expected so don't worry if you see them.

**Comment by dn14** [comment]
Thank you very much sir ,for your help.i will do that.
regards
dona nipin

**Comment by dn14** [comment]
dear sir
kindly find the attached screenshot of the issue.
thank you again.

**Comment by brandonhellman** [comment]
Should be fixed in v2.6.10

**Comment by dn14** [comment]
thank you sir.
