### ISSUE TITLE
HIT Catcher repeatedly stops searching

### ISSUE THREAD

**Issue by HugoLME** [brandonhellman/mturk-suite#228]
Since recently, Hit Catcher has been stopping every few minutes. Today it has been nearly unusable. I can restart it by either:

1. Refreshing the tab, or...
2. Clicking "Pause" twice.

I only know that there's a problem when, usually after a spell of not getting HITs, I notice that the search numbers have not changed in a while.

I use Mturk Suite v2.6.9 in Chrome. No PRE's. I had Hit Catcher's speed at 1000 ms. Raising that to 1100 and later 1200 made no difference.

**Comment by brandonhellman** [comment]
When it gets stuck again, can you open the console log (`ctrl + shift + j`) and paste the last few errors (or screenshot).

There will be a bunch of 422 (Unprocessable Entity) errors, those are expected so don't worry if you see them.

**Comment by remu007** [comment]
I also face same issue. I give you full picture of this problems.
![1](https://user-images.githubusercontent.com/48662693/57563033-b1772e80-73ba-11e9-87d6-33346839568f.png)
![2](https://user-images.githubusercontent.com/48662693/57563034-b1772e80-73ba-11e9-8f0f-493bab950aca.png)

**Comment by remu007** [comment]
If you have need more details. I will give you. I hope you solve this issue as soon as possible. Thank you very much.

**Comment by brandonhellman** [comment]
Should be fixed in v2.6.10
