### ISSUE TITLE
Hit Catcher Freezes Reopened

### ISSUE THREAD

**Issue by GitHubGitHub123321** [brandonhellman/mturk-suite#230]
Thank you so much for responding to me. I'm using the current version. It freezes in FireFox or Chrome when I have more than like 3 catchers open. Is this a RAM issue, perhaps an Internet issue?

Thanks again!

**Comment by brandonhellman** [comment]
You should only have once Catcher tab open, with multiple watchers (either on or off) in that one Catcher tab. Having more than one open will have them start triggering more Page Request Errors (rate limiting) and causing them to trip each other up.

**Comment by GitHubGitHub123321** [comment]
That's my current setup. Maybe it's my memory usage. Seem to be using 60%.

**Comment by brandonhellman** [comment]
I'm not sure then, sorry. You could try backing up your HIT Tracker, include/block lists and anything else and then reinstalling MTS and see if that helps anything.

**Comment by GitHubGitHub123321** [comment]
okay, thanks
