### ISSUE TITLE
Issues after update, alerted to hit caught minutes after it's caught, hits that aren't caught not showing in watcher when using new button

### ISSUE THREAD

**Issue by TurkEmup** [brandonhellman/mturk-suite#232]
When using the new buttons for Once and Panda, I'm encountering problems. The catcher will alert me a few minutes after the hit has been caught. It will show up on the catcher that it's been caught and a a minute or two (or more) it will voice alert me. The uncaught hits also don't show up on the watcher until they're caught. The regular right click option still seems to be working fine.

ETA: it seems that some of them are still showing up on the watcher, just with the name of the requester, unlike before where it wouldn't show that until caught.

**Comment by chasegeaton** [comment]
Are you running HIT Catcher in it's own browser window with no other tabs open in that window?

**Comment by Vren13** [comment]
> Are you running HIT Catcher in it's own browser window with no other tabs open in that window?

Should I be running hit catcher on its own separate window?

**Comment by chasegeaton** [comment]
Yes. You should have a Chrome window with one tab that is running Hit Catcher with no other tabs open in that window. Chrome [throttles](https://developers.google.com/web/updates/2017/03/background_tabs#background_timer_alignment) background tabs so having Hit Catcher in its own Chrome window will allow you to set timers shorter than 1 second.

**Comment by Vren13** [comment]
> Yes. You should have a Chrome window with one tab that is running Hit Catcher with no other tabs open in that window. Chrome [throttles](https://developers.google.com/web/updates/2017/03/background_tabs#background_timer_alignment) background tabs so having Hit Catcher in its own Chrome window will allow you to set timers shorter than 1 second.

Thank you very much.
