### ISSUE TITLE
HIT Goal Reward Goal 

### ISSUE THREAD

**Issue by madhanprashanna** [brandonhellman/mturk-suite#234]
<This is not issue but need some options>

1) set goal gone after refresh the page, to set goal i have to set and Enter two to three times to fix the target goal

Requests : 
1)" Reset" option for goal (pleaseeeeee)
2) auto reset of goal time starts from reseting time upto 24 hrs
3) coloring for HITs in HIT catcher list useful to spot important hit easyly 
(boxes in mild coloring and coloring option in settings of HIT)

sorry this is 1 issue and remaining is suggestion to improve your work
and i am big fan of your work thanks a lot for your support

Window 7 x86
HP lap 
google chrome (latest)

**Comment by chasegeaton** [comment]
Are you talking about the HIT and Reward Goals at the top of the MTurk page?
