### ISSUE TITLE
Two questions about returned/abandoned hits

### ISSUE THREAD

**Issue by kimadagem** [brandonhellman/mturk-suite#235]
Earlier today I was forced to return a hit because the survey site I'd already returned that assignment. That didn't make sense - the hit was still open - but I sent it back. It got me wondering though if I could have a list of all the hits I've returned since I started using MTS; that might be helpful in the future. I can see these hits if I pull everything for a specific date range but I can't find a way to filter out all the other hits. Is there a way to do that?

Also, when I was looking at this week's list I noticed that those hits are all labelled "abandoned" when they weren't, they were returned (no expired timers). Is this just a labeling change or is this info being pulled from MTurk, in which case I'm wondering if they've changed something.

**Comment by brandonhellman** [comment]
There isn't a way to search for abandoned/returned HITs. That shouldn't be difficult to add under the "view" dropdown filter in the History.

Returned/abandoned tracking is all handled by MTS so it'd just be a labeling change. MTurk doesn't give that data as far as I could find.
