### ISSUE TITLE
Rating for each hit stopped showing up in top left

### ISSUE THREAD

**Issue by GitHubGitHub123321** [brandonhellman/mturk-suite#236]
For some reason, like 10 minutes ago, when I click on a hit I have accepted there is no longer a rating beside the specific job either at the top left or on the queue's screen. 

![image](https://user-images.githubusercontent.com/50556830/58766098-d63d6c80-8548-11e9-8536-dec0df9df84b.png)

**Comment by brandonhellman** [comment]
Those ratings and stuff are connected to the Turkerview API which is having some trouble right now. Whenever that gets fixed the ratings and everything will come back.

**Comment by GitHubGitHub123321** [comment]
Thank you!

Andrew 

    On Sunday, June 2, 2019, 3:36:52 PM EDT, Brandon Hellman <notifications@github.com> wrote:  
 
 
Those ratings and stuff are connected to the Turkerview API which is having some trouble right now. Whenever that gets fixed the ratings and everything will come back.
