### ISSUE TITLE
what happened to the mturk suite extention? it hasnt been available for 2 days.

### ISSUE THREAD

**Issue by Scottyc2112** [brandonhellman/mturk-suite#238]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by brandonhellman** [comment]
The Google Chrome Store updated some of its policies and I'm trying to get MTS back within them so MTS can get relisted.

**Comment by Earlpengo** [comment]
we need mturk suite back

**Comment by brandonhellman** [comment]
Back up on both Chrome and Firefox web stores.
