### ISSUE TITLE
Hit Finder stalling.

### ISSUE THREAD

**Issue by LLL-GitHub** [brandonhellman/mturk-suite#24]
I noticed that when Hit Finder stalls and gives the 281 error in console it shows the times in the Hits Log incorrectly. It always jumps backwards (see enclosed pics). Hit Tracker also stops working. If you try to sync with the daily it just freezes on "Syncing... checking last 45 days." Also if you hit the extension button it does nothing until you refresh Hit Finder. Then everything works instantly. Hope this was helpful. 

![screenshot 834](https://user-images.githubusercontent.com/36159244/35805606-263fb27a-0a42-11e8-806a-83a71075ffb9.png)

![screenshot 835](https://user-images.githubusercontent.com/36159244/35805584-088d3554-0a42-11e8-8d90-32295b7fff56.png)

**Comment by brandonhellman** [comment]
I need browser and browser version at minimum.

Times are working as intended https://github.com/Kadauchi/mturk-suite/wiki/HIT-Finder#sections

What were the errors if you recall (I don't need all 281, most will be duplicates)

Are there any errors on HIT Tracker?

The dropdown issue is tied to HIT Finder, so when that gets fixed this should also get fixed.
