### ISSUE TITLE
HIT Finder is not work

### ISSUE THREAD

**Issue by remu007** [brandonhellman/mturk-suite#242]
HIT Finder is not work perfectly. If I start HIT finder within 1 to 2 minutes stop find HIT Total Scans going faster than faster like 1 minute Total Scans 10000. I hope you understand this issue. So please try to solve this issue. I give you a screen short of this problem. Please solve this issue as soon as possible.
![se](https://user-images.githubusercontent.com/48662693/61727341-fe9d5680-ad94-11e9-99ba-9fce2ec996b4.png)

**Comment by remu007** [comment]
I give you more details about this issue please 2 minute HIT finder page screenshot and error.
![sw](https://user-images.githubusercontent.com/48662693/61729240-98b2ce00-ad98-11e9-97a3-e7136c0e029f.png)

**Comment by Kadauchi** [comment]
Can you expand your settings and give me a screenshot of those too?

**Comment by brandonhellman** [comment]
The issue is your speed setting. You shouldn't have it set that low. Don't have it any lower than 1000ms (1s).

**Comment by remu007** [comment]
Hello dear sir I flow your instruction but still have same problems. So please do something for me.
![T4](https://user-images.githubusercontent.com/48662693/62014885-5c340780-b1c8-11e9-9fe0-6e8aed68b8bd.png)

**Comment by brandonhellman** [comment]
Try lowering the page size setting to 50.

**Comment by remu007** [comment]
Hello sir. I really do not understand what I do. You mean I send you this problems Console page size lowering 100 to 50. After I take a screenshot Console page and send you. I am really sorry to say you If I wrong please give me full details what I do.

On the other hand I give you this problems 1 more news. If this extension delete from my browser and again reinstall. After reinstall this MTS HIT Finder work fine 15 to 25 minute. Between this time again continue this problems. I hope you understand. Thank you very much.

**Comment by remu007** [comment]
OK I got it. I just lowering the page size setting to 50. but still same issue. This problems still continue.
![UP](https://user-images.githubusercontent.com/48662693/62071525-8df7ad80-b25e-11e9-92e8-509dd8811356.png)
