### ISSUE TITLE
Return review integration in MTS

### ISSUE THREAD

**Issue by Masterbah1234** [brandonhellman/mturk-suite#248]
This isn't an issue but more a feature request. I don't know if it's the right place to post it.

Would there be a way to integrate the return reviews in HIT finder? Maybe just the triangle with the exclamation point that can be found on the HIT itself, maybe even have the 2-3 most recent pop-up when hovering over the HIT title or something like that. I know return review come from TVJS and not from you, but I'm wondering if the info could be fetched and displayed, as most people don't preview HITs before accepting them. 

It would increase their usefulness as a "don't accept the HIT" rather than "see, it's bugged for everyone" (plus, it's a pain when it's an endor that's bugged).

**Comment by brandonhellman** [comment]
You found the correct place.

Good news:
The idea sounds great and I, I'd just have to be check that it won't negatively affect the TV API with the extra requests.

Not so good news:
I'm no longer adding new features to MTS v2. I have another project that I need to finish first that is needed to start developing MTS v3.

**Comment by Masterbah1234** [comment]
Thanks for the reply, good to know that you're considering adding it in the future. How of curiosity, to you have an idea of a time frame for development of MTS v3 (broad terms, like 6months or 3years)?

Thanks for the great work btw.

**Comment by brandonhellman** [comment]
My goal is to have v3 out before the end of the year

**Comment by Masterbah1234** [comment]
Excellent news, thanks for the info and good luck!
