### ISSUE TITLE
Can't import/add to blocklist

### ISSUE THREAD

**Issue by kimadagem** [brandonhellman/mturk-suite#25]
I used the "delete" option with the intention of starting over, with a new list, from Hit Scraper (to remove old hit titles, mainly). The list was deleted but I haven't been able to get the new list into the Finder. I've tried Add using a manual copy/paste - which I think is what I did the first time - and Import using a text file (copied straight from Hit Scraper) but neither has worked. Am I missing something?

I have a related question. I think you mentioned at one time that your blocklist uses IDs rather than strings. I do have IDs of all the requesters I've blocked so if there's a way to use that data that might be more effective, since I wouldn't have to add all the different names a requester has used.  I don't have IDs for the hits but I can manually add those as the Finder pulls them up; I usually clear those once a week anyway so there aren't usually a lot.

**Comment by brandonhellman** [comment]
HIT Scraper is abandon ware at this point and the import into HIT Finder's block/include list format is really crappy because of the no requester/group id's so it been dropped from MTS.

I'll make a userscript converter and link it here before closing.

**Comment by brandonhellman** [comment]
https://greasyfork.org/en/scripts/38206-hit-scraper-to-mturk-suite
