### ISSUE TITLE
Pop-ups not working 

### ISSUE THREAD

**Issue by ladyinblack64** [brandonhellman/mturk-suite#251]
I have not used MTS in several months. I just reinstalled it on two separate browsers (Firefox and Chrome). I used to get popups telling me when I had a hit but they are no longer working. 

Can someone please help? Thanks!

**Comment by brandonhellman** [comment]
Is the sound button green for the Watcher in HIT Catcher?

**Comment by ladyinblack64** [comment]
Hi, Brandon: 

Yes, it is green. 

Sandra

    On Friday, August 23, 2019, 4:07:38 PM EDT, Brandon Hellman <notifications@github.com> wrote:  
 
 
Is the sound button green for the Watcher in HIT Catcher?

**Comment by brandonhellman** [comment]
Can you open the console log <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>f12</kbd> and take a screenshot of any errors after a Watcher catches a HIT and doesn't make a sound.

**Comment by brandonhellman** [comment]
Sorry, I just realized you were talking about desktop notifications. HIT Catcher doesn't have them but it is something that will be added in `v3`.
