### ISSUE TITLE
Edit Hit Tracker Database?

### ISSUE THREAD

**Issue by cattcali** [brandonhellman/mturk-suite#253]
So, I forgot to sync my Hit Tracker for a couple of months and now it's showing that a bunch of hits from a couple of months ago are still pending.  Is there some way to edit those hits to paid through the extension?  If not, do you have any suggestions on how to edit the .json backup file?

**Comment by brandonhellman** [comment]
This isn't documented anywhere but you can export and then reimport the database. The importer fixes any old pending HITs.

**Comment by cattcali** [comment]
Oh nice.  Thank you :)
