### ISSUE TITLE
HIT Tracker disabled still shows

### ISSUE THREAD

**Issue by Wolf68k** [brandonhellman/mturk-suite#254]
**Describe the bug**
I'm not sure of this is a bug or a "feature" but I would think if I uncheck HIT Tracker under Enable Scripts it should not only hide the options but also remove it from mturk as well.
Instead I have to uncheck all of the options to remove it from mturk.

**To Reproduce**
1. Go to MTS options
2. Uncheck **Hit Tracker** and notice the HIT Tracker options disappear
3. Refresh mturk.com HIT page, the tracker info is still there.

**Expected behavior**
I would expect the tracking info to be removed from mturk as well as hide the options.

**Desktop (please complete the following information):**
 - OS: Win 7 Pro
 - Browser: Firefox 69.0.1
 - Version: 2.6.18

**Additional context**
With this being a feature now on mturk, although in beta, this feature here seems redundant.

**Comment by brandonhellman** [comment]
Yup, that's a bug for sure. 

Do you mind providing some additional information about this new feature? I haven't seen anything but I know MTurk adds new features in staged rollouts.

**Comment by Wolf68k** [comment]
The new feature is at the top of the page.
Screen shot https://i.imgur.com/S92HL8V.png
Which also brings up another issue, If you look closely there is some text in there besides the numbers but it's too dark. I would think that should be an easy fix within the themes.

**Comment by brandonhellman** [comment]
Oh haha, the goal bars. I completely spaced on those.

The bug will ofc still get fixed but I would recommend only disabling Display Earnings. Display Counts shows you the checkmark/question marks next to the HITs you've done and Live Update saves all of the answers you submit which is a nice thing to have in case of an unfair rejection.

Thank you, I'll add that to the list. The themes have quite a few little quirks.
