### ISSUE TITLE
Request: Hide Requester Information popup

### ISSUE THREAD

**Issue by Wolf68k** [brandonhellman/mturk-suite#255]
**Describe the request**
Now when you mouse over a HIT a popup showing some requester information shows up

**To Reproduce**
1. Mouse over any HIT

**Expected behavior**
It gets annoying at time, more so the placement of the popup. It would be nice to be able to remove it.

**Screenshots**
https://i.imgur.com/N9NkCan.png

**Comment by brandonhellman** [comment]
This and a few other options for it will for sure be coming with the v3 release.

**Comment by auntgrammy** [comment]
If possible, I'd prefer this to be an option and not something that's done away with altogether. I've used this info as it's direct from Amazon about the requester and shows their average Amazon rating and approval time. It's on the Mturk Hit page only when you hover over the Amazon "a" logo next to the Req name.

**Comment by brandonhellman** [comment]
> If possible, I'd prefer this to be an option and not something that's done away with altogether. I've used this info as it's direct from Amazon about the requester and shows their average Amazon rating and approval time. It's on the Mturk Hit page only when you hover over the Amazon "a" logo next to the Req name.

Hover over the Amazon "a" logo is actually going to be one of the options added so you'll be covered.
