### ISSUE TITLE
Theme doesn't always kick in

### ISSUE THREAD

**Issue by Wolf68k** [brandonhellman/mturk-suite#256]
**Describe the bug**
Some times after submitting a HIT and returning to the list the theme does not always come back.

**To Reproduce**
Not always possible to reproduce since this is random.

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro
 - Browser: Firefox 69.0.1
 - Version: 2.6.12 (I'm assuming you mean add-on version)

**Comment by brandonhellman** [comment]
Thanks for the report. I'll be sure to check into this too when I get around to the other Theme issues.
