### ISSUE TITLE
Once / Panda buttons gone on HIT preview page

### ISSUE THREAD

**Issue by LJTurk** [brandonhellman/mturk-suite#26]
Ever since the update this morning I'm not seeing the ability to add HITs to HIT Catcher once I go to preview them from HIT Finder.

**Comment by bmcg2201** [comment]
Same problem here, seems like Kadauchi is working on it already.  Thanks for the great program Kad.

edit: using latest version of chrome

**Comment by brandonhellman** [comment]
Fixed v2.1.10
