### ISSUE TITLE
Prolific chrome extension no longer works??

### ISSUE THREAD

**Issue by Theguru123** [brandonhellman/mturk-suite#261]
When you try to logon it no longer accepts the password on prolifoic, you disable the extension it works fine??

Been working fine for a while suddenly it seems prolific have done somethiing..Even support said if you use the prolific assistant please disable it!!

Tried the usual tricks uninstalling, reinstalling both chrome and extension still the same problem

Please update??

**Comment by brandonhellman** [comment]
I'll check it out, thanks for the report!

**Comment by brandonhellman** [comment]
Can you try clearing Prolific's cookies and seeing if that helps?

1. Click the lock next to the address in the address bar.
2. Click "Cookies"
![](https://i.gyazo.com/51dae662a29e24c2d4cf171c227e2b65.png)

3. Select anything with "prolific"
4. Click remove
5. Repeat 3+4 until there are no more "prolific" cookies left
![](https://i.gyazo.com/a4116b5089d4565717d5f4396e246a9d.png)

**Comment by brandonhellman** [comment]
Linking a Reddit post about this issue.

https://www.reddit.com/r/ProlificAc/comments/ea3xtq/login_issues_on_chrome_and_sometimes_ff/
- Clearing cookies works (temp) but then doesn't at all for some people...
- Happening without PA installed
- Happening only with PA installed

**Comment by brandonhellman** [comment]
Oof, just realized this is under the wrong repository. No matter, this issue has been resolved.

https://www.reddit.com/r/ProlificAc/comments/ebd0ws/login_issues_should_now_be_resolved_and_a_note_on/
