### ISSUE TITLE
Deleting multiple items at once in HIT Catcher?

### ISSUE THREAD

**Issue by usetheforce1** [brandonhellman/mturk-suite#262]
Is there any way to delete multiple items at once in HIT Catcher? I have several hundred (maybe even 1000+) old hits sitting just sitting in my HIT Catcher. Since I've only been doing this a month or so, I try to grab almost every HIT I can. I don't want to take the time to delete each one, one at a time. Also, I've noticed my catcher is not picking up HITs like it was in the beginning. Even thou these old HITS are not running, could they cause the program to slow down?

**Comment by brandonhellman** [comment]
You can ctrl+click to multi-select then press the delete key to delete multiple at once.

Old catchers that aren't running won't slow the program down by any perceivable time. Catching less is probably just down to luck/holidays.

**Comment by usetheforce1** [comment]
Awesome thanks Brandon!
