### ISSUE TITLE
Include list match found, not displaying the "found" item

### ISSUE THREAD

**Issue by AlienGit** [brandonhellman/mturk-suite#27]
Current chrome. Win 7.

Include list match found announces. Nothing shows up. 

or

Something shows up 30s to a minute later, multiple, multiple times. 8-12 times.

**Comment by brandonhellman** [comment]
What are your HIT Finder settings?

**Comment by AlienGit** [comment]
What's the best way to get that to you? Screenshot or is there a file somewhere?

**Comment by brandonhellman** [comment]
Really just need the speed and page size.

**Comment by AlienGit** [comment]
4000ms, 100 is current, but also does it at 8000ms

**Comment by brandonhellman** [comment]
Try with a size of like 30-50 and see if it still does it or takes longer for it to actually break. I think I'm on the right track of fixing this and several other issues that are stemming from this.

**Comment by AlienGit** [comment]
Hi @Kadauchi I think your newest release has fixed the issue, I'll reopen if it starts happening again.

Thanks for the hard work!

**Comment by AlienGit** [comment]
Mmm, well it still seems to be missing them. I knew when I posted my other comment it would happen quickly.
