### ISSUE TITLE
I am having trouble reinstalling MTURK Suite after refreshing Firefox Browser. Is this the lastest download link for Firefox? If so, The link is not working for me. Firefox  https://addons.mozilla.org/en-US/firefox/addon/mturk-suite/

### ISSUE THREAD

**Issue by BluAngelComic** [brandonhellman/mturk-suite#273]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pietro395** [comment]
yes it's not available...

**Comment by brandonhellman** [comment]
Thanks for bringing this to my attention. I am working on getting it relisted asap.

**Comment by brandonhellman** [comment]
MTS has been relised.
