### ISSUE TITLE
Amazon shows HIT Details in HIT now, so MTS HIT Details Enhancer not needed. (Not a complaint/nag/whatever, just letting you know)

### ISSUE THREAD

**Issue by cr4m3r** [brandonhellman/mturk-suite#30]
See title.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by cr4m3r** [comment]
The react hit info is in a span instead of div now...J

JSON.parse(document.querySelector(`span[data-react-class="require('reactComponents/common/ShowModal')['default']"]`).dataset.reactProps) 

Don't know if that affects other parts of MTS???

**Comment by brandonhellman** [comment]
This is being replaced by a new script in the next update.

Nope, just using the attribute to select elements. https://github.com/Kadauchi/mturk-suite/blob/ffbc5b9b2fbe2b9bd053b35c780dfb213a79cca5/js/mturk-react.js#L7
