### ISSUE TITLE
sync problem

### ISSUE THREAD

**Issue by Suban77** [brandonhellman/mturk-suite#31]
its not sync 45 days please fix this bug

**Comment by brandonhellman** [comment]
Need more information. Browser, browser version.

**Comment by Suban77** [comment]
Google Chrome 
Version 64.0.3282.140 (Official Build) (64-bit)

**Comment by brandonhellman** [comment]
Which message is HIT Tracker getting stuck on when it fails to sync the last 45 days?

**Comment by Suban77** [comment]
Fetching queue

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by brandonhellman** [comment]
Are there any console errors and if there are what are they? `ctrl+shift+j` to open the console, errors will be red.

**Comment by Suban77** [comment]
fetchQueue
ƒ fetchQueue(date) {
  syncingUpdated(date, `fetching queue`)

  return new Promise((resolve) => {
    (async function fetchLoop () {
      try {
        const response = await fetch(`https://wor…

**Comment by Suban77** [comment]
function fetchQueue (date) {
  syncingUpdated(date, `fetching queue`)

  return new Promise((resolve) => {
    (async function fetchLoop () {
      try {
        const response = await fetch(`https://worker.mturk.com/tasks?format=json`, {
          credentials: `include`
        })

        if (response.ok && response.url === `https://worker.mturk.com/tasks?format=json`) {
          const json = await response.json()
          resolve(json)
        } else if (response.url.indexOf(`https://worker.mturk.com/`) === -1) {
                    // we are logged out here
        } else {
          setTimeout(fetchLoop, 2000)
        }
      } catch (error) {
        setTimeout(fetchLoop, 2000)
