### ISSUE TITLE
Sync not resetting weekly earnings on sunday

### ISSUE THREAD

**Issue by TurkIngiNtheusa** [brandonhellman/mturk-suite#32]
Syncing does not reset the weekly earnings to $0.00 on Sunday.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by brandonhellman** [comment]
Intended outside of it not saying "last week" on Sunday's since the weekly total on Sunday is just the daily.

**Comment by ImBeyonceAlways** [comment]
Mine still hasn't reset as of Monday, 7:45 AM EST. No luck with uninstalling/reinstalling. Any suggestions?
