### ISSUE TITLE
Blocklist isn't accepting import from Hit Scraper

### ISSUE THREAD

**Issue by kimadagem** [brandonhellman/mturk-suite#34]
I know this was set up before because it did work for me; I remember getting a message asking if the list was from Hit Scraper - but I'm not seeing that now, and the Finder doesn't seem to be recognizing what's in the blocklist.

I wanted to start over with the list I had, to remove old hit names, so I used the Delete function; that worked fine. I then tried Add to paste what I'd copied from the Scraper but nothing showed until I pasted into both the Name and Match fields. The list contents then showed but the next search I did pulled up hits from requesters on the blocklist.  I've tried this with Strict Matching both on and off; it doesn't make a difference.

I also tried Import, with the Scraper's blocklist in a text file; I was able to select the file but nothing shows in the blocklist window. Maybe it needs a different format?

I do have a database with all my blocked requesters, including their IDs. I think you said that your blocklist uses IDs rather than strings so if there were a way for me to import the IDs that would be great, especially since I wouldn't have to worry about the requester names' changing. I'm just not sure what file format to use.

**Comment by brandonhellman** [comment]
Duplicate #25
