### ISSUE TITLE
Review site links on daily status page aren't working

### ISSUE THREAD

**Issue by kimadagem** [brandonhellman/mturk-suite#35]
These are the links to Turker View, TO1, and TO2. I can get the box to show and the target is displaying at the bottom but the pages won't open. If it weren't for the targets' displaying I would think the links weren't live.

I'm pretty sure I've brought this up before but I can't remember if it was resolved; here's a screenshot I just took:

![mts to links screenshot](https://user-images.githubusercontent.com/26679556/36078488-f5e388c4-0f44-11e8-872f-960ad226af3a.jpg)

I've never tried inserting an image that way here before so if it doesn't work here's an alternative:
https://imgur.com/a/7NrCU

What's showing here is the TO2 link but the same problem is happening with the Turker View and TO1 links.

**Comment by brandonhellman** [comment]
Still haven't had time to properly address this. Were you using Chrome or FF? I forgot which.
