### ISSUE TITLE
Couple suggestions for HIT Catcher

### ISSUE THREAD

**Issue by Fliksan** [brandonhellman/mturk-suite#37]
Just had a couple suggestions for HIT Catcher. 

1 is a button to delete all watchers, when I start mturk back up for the day I tend to have to delete like 10-15 HITs I had on watch, and you have to delete them all individually. It's not a huge deal but a delete all button would save a bit of time.

2nd suggestion is to add a time that you added the HIT to watcher. You can kinda guess how long you've had a HIT being watched by # of scans, but just having the time you added the HIT in the information box would be useful.

**Comment by brandonhellman** [comment]
You can `ctrl + click` watchers to highlight them then press the `delete` key and it will batch delete after confirmation.

I'll add the time under the watcher settings when I get to updating HC with other stuff, solid suggestion.
