### ISSUE TITLE
Requester ID

### ISSUE THREAD

**Issue by yuvaraja839** [brandonhellman/mturk-suite#4]
we want Requester ID option in hit catcher. to collect tha all job in that Requester ID

**Comment by yuvaraja839** [comment]
requester ID to find any hits. If you change to the search mode you must have a Requester ID filled in or it won't let you save it. The script can't figure out requester ID's by a panda because usually mturk doesn't display that info on a hit. When the job is in Search Mode it will do a search and try to panda the top three highest paid hits it finds.

**Comment by brandonhellman** [comment]
Added to projects. https://github.com/Kadauchi/mturk-suite/projects/1#card-6990607
