### ISSUE TITLE
Mturk Suite scroll to workspace option is cutting off the hit now.

### ISSUE THREAD

**Issue by Venusx** [brandonhellman/mturk-suite#42]
Mturk suite was updated, and now the requester name, amount of hits, hit worth, and time remaining remain always at the top. This is an issue with some hits. When the workspace scrolls all the way up, this top bar blocks half of what you are supposed to be seeing, making it so you can not complete the hit unless you scroll the window down. Making scroll to workspace useless.

## Expected Behavior
The hits should not be scrolling all the way up and being blocked by that tip bar.
Please remove the piece of code the now keeps that amazon information always on top. It was better previously.

## Current Behavior
https://i.imgur.com/4cr0bSe.png?2 This image shows the issue. This isn't the only hit with this issue, but the top bar that is always on top now blocks part of the hit. Making it so you have to scroll down to see what you are even looking at.

## Possible Solution
Remove the new feature that keeps the amazon information always at the top. It is blocking data from hits.

## Context
This has made mturk suite a nuisance to deal with. I have to uninstall it multiple times a day now when certain hits are up or I have to move it to another browser.

## Your Environment
This is not an issue with my browser, as this happens with both chrome and firefox on multiple PC's. This is an issue with the latest update.

**Comment by brandonhellman** [comment]
I'll have Workspace Expander check to see if the sticky header is active and account for it. Temp fix would be to disable HIT Details Sticky in the options.

**Comment by Venusx** [comment]
Awesome! Thanks for looking into this.
