### ISSUE TITLE
Hit Tracker Stuck

### ISSUE THREAD

**Issue by mnguy1970** [brandonhellman/mturk-suite#43]
Hit Tracker says fetching and gets stuck there. 

Version 64.0.3282.167 (Official Build) (64-bit) Chrome 

worker.mturk.com/status_details/2018-02-18?page_number=1&format=json Failed to load resource: the server responded with a status of 400 (Bad Request)
hit_tracker.js:432 GET https://worker.mturk.com/status_details/2018-02-18?page_number=1&format=json 400 (Bad Request)
fetchLoop @ hit_tracker.js:432
hit_tracker.js:432 GET https://worker.mturk.com/status_details/2018-02-18?page_number=1&format=json 400 (Bad Request)
fetchLoop @ hit_tracker.js:432
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
hit_tracker.js:432 GET https://worker.mturk.com/status_details/2018-02-18?page_number=1&format=json 400 (Bad Request)
fetchLoop @ hit_tracker.js:432
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
hit_tracker.js:432 GET https://worker.mturk.com/status_details/2018-02-18?page_number=1&format=json 400 (Bad Request)
fetchLoop @ hit_tracker.js:432
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
hit_tracker.js:432 GET https://worker.mturk.com/status_details/2018-02-18?page_number=1&format=json 400 (Bad Request)
fetchLoop @ hit_tracker.js:432
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
hit_tracker.js:432 GET https://worker.mturk.com/status_details/2018-02-18?page_number=1&format=json 400 (Bad Request)
fetchLoop @ hit_tracker.js:432
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
hit_tracker.js:432 GET https://worker.mturk.com/status_details/2018-02-18?page_number=1&format=json 400 (Bad Request)
fetchLoop @ hit_tracker.js:432
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
setTimeout (async)
fetchLoop @ hit_tracker.js:477
async function (async)
fetchLoop @ hit_tracker.js:430
hit_tracker.js:432 GET https://worker.mturk.com/status_details/2018-02-18?page_number=1&format=json 400 (Bad Request)

**Comment by aesha-CORUS** [comment]
I have this exact same issue, first noticed yesterday

**Comment by aesha-CORUS** [comment]
Google Chrome is up to date
Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by aesha-CORUS** [comment]
mnguy1970 where did you get that log so I can provide mine as well?

**Comment by brandonhellman** [comment]
@aesha-CORUS `ctrl + shift + j`  to open the console and then it should be in there.

**Comment by aesha-CORUS** [comment]
Thanks @Kadauchi 

Ok, so I am getting something else.. but same effect. No hits listed.

hit-finder.js:99 GET https://worker.mturk.com/?sort=updated_desc&page_size=150&filters%5Bmasters%5D=false&filters%5Bqualified%5D=true&filters%5Bmin_reward%5D=1&filters%5Bsearch_term%5D=&format=json 422 (Unprocessable Entity)

If I send the URL direct in chrome I get:
{"errors":"The provided criteria is not valid. Please recheck the URL or browse \u003ca href=\"/?filters%5Bqualified%5D=true\"\u003eall HITs\u003c/a\u003e available."}

**Comment by brandonhellman** [comment]
@aesha-CORUS that is HIT Finder not HIT Tracker. Change page size to a value between `1 - 100`.

**Comment by aesha-CORUS** [comment]
OOPS.. my bad. Thanks for the info though.. it works now.
