### ISSUE TITLE
Projected earnings this week.

### ISSUE THREAD

**Issue by cattcali** [brandonhellman/mturk-suite#45]
Projected earnings this week is still showing earnings from last week.

I am using v2.1.12
Chrome Version 65.0.3325.88 (Official Build) beta (64-bit)
Windows 10 Home 64-bit

**Comment by Leviathon2** [comment]
Same. I'm on PST time. It's currently 1:04 PM.

**Comment by brandonhellman** [comment]
Fixed in v2.1.13

**Comment by JrRandy** [comment]
@Kadauchi This happened again on this weeks rollover.  I still have last week's stats showing running 2.1.14

**Comment by cattcali** [comment]
Yeah, the update didn't fix it.
