### ISSUE TITLE
Issue regarding sync after the last update

### ISSUE THREAD

**Issue by balder85** [brandonhellman/mturk-suite#46]
## Expected Behavior
After the last update, I couldn't get the sync to update all the Tracker Overview, and it stuck with the old data before the update, the results seem to be freezed.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
After the last update, I couldn't get the sync to update all the Tracker Overview, and it stuck with the old data before the update, the results seem to be freezed.

**Comment by JrRandy** [comment]
Same issue here.  If you Sync and then manually refresh the page, the data will update.  The page does not seem to refresh itself any longer.
