### ISSUE TITLE
Themes not working on tracker - defaults to default

### ISSUE THREAD

**Issue by TurkIngiNtheusa** [brandonhellman/mturk-suite#47]
The themes stopped working on hit tracker. Seem to work properly elsewhere.

When opening tracker the theme should match the other scripts.

I have darkly enabled but default is used. This occurs only on tracker.

1. Set your themes to darkly
2. open tracker

I am using the latest MTS update on Windows 10 in chrome

**Comment by brandonhellman** [comment]
Fixed v2.1.14
