### ISSUE TITLE
Add elapsed time timer

### ISSUE THREAD

**Issue by Tjololo12** [brandonhellman/mturk-suite#5]
The old mturk had a timer which started at 0, and ended at $timeallotted when it expired. The new mturk interface has a timer which starts at $timeallotted and ends at 0...Would it be possible to either replace this timer, or add a second one, showing the time elapsed since starting the hit? I find that much more interesting than time expired, and I hate mathing to get the answer...why should I math when my computer can do it for me?

**Comment by brandonhellman** [comment]
This is the new default from MTurk now.
