### ISSUE TITLE
Hit Tracker does not import correctly

### ISSUE THREAD

**Issue by 3854** [brandonhellman/mturk-suite#51]
I had an unrelated issue with Chrome Canary (67.0.3364.0 64-bit) which required a reinstall, and cleared my HIT Tracker history in the process. When I imported my most recent backup, I noticed that the numbers were way off. I've since tried clearing the database and importing several backups from the last few months, but when I check my history, my daily totals are still much higher than they should be. When I look at my Requester numbers, it says that I've completed significantly more HITs for certain requesters than I actually did. These numbers were accurate before I uninstalled the browser. I'm also having the same problem in Chrome 65.0.3325.146 64-bit after importing.

Pinterest is one of the offending requesters, and my daily totals are much higher on days where I did a lot of their HITs, so it seems like HIT Tracker is counting returned HITs from the backup as having been paid, instead. The Return/Abandoned column in my history is completely blank, and my numbers from before 12/15/17 seem to be correct.

**Comment by brandonhellman** [comment]
I've found the issue. I'll push a fix for it today.
