### ISSUE TITLE
Projected earnings  not resetting

### ISSUE THREAD

**Issue by reaper9897** [brandonhellman/mturk-suite#54]
For the past two weeks the weekly earnings does not reset.  It just keeps adding to the total from the previous week.  I am using the  latest version of Chrome.  I reinstalled Mturk Suite last week and it seemed to fix the issue.  Now this week it's back to the same problem and reinstalling does not seem to help.  Is there a workaround for this?  Thanks!

**Comment by JrRandy** [comment]
This has not worked consistently since the update to have Sundays show "last weeks" earnings.  Can we revert back to the original method where it worked?

**Comment by xchou** [comment]
My Hit Tracker has just completely stopped working

**Comment by JrRandy** [comment]
If it's not working at all, that is a seperate issue.  If your "this week" stopped working, that's because the week range is hard coded requiring a weekly update to the extension.  Not sure why it's done that way, but it is.

**Comment by brandonhellman** [comment]
Duplicate #17 
Issue won't affect users from here on out.
