### ISSUE TITLE
MTS and all plugins work once, then stop opening in Chrome (once you close and open new tabs)

### ISSUE THREAD

**Issue by doleapfrog** [brandonhellman/mturk-suite#58]
SUPER NEW to turking and all things computer but wanted to ask.  Over the past month or so I've notice MTS and all other plugins in Chrome that help with MTurk (Turkopticon, Screencastify, hell even Pinterest) stop working after one open.  I have to close everything and restart Chrome every time I need to reopen.

Appreciate any help!

## Expected Behavior
I feel like Chrome plugins should work every time.  I do check Plugin Settings and they are all on and not switched off.

## Current Behavior
Described above

## Possible Solution
No idea, I am just learning this stuff,

## Steps to Reproduce (for bugs)

1. Open Chrome
2.Sign Into MTurk
3.Click on MTS Plugin
4.Do some work/Hits
5.MTS tab gets closed accidentally, go to press button and no drop down opens to allow to find more hits.

## Context
Wastes a ton of time due to restarting.  I've googled the heck out of this and it leads no where, only to some old posts about Flash plugins from 2016-2017 -- but they don't make sense in this context.

## Your Environment

* Version used:  65.0.3325.181
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows 10 10.0.15063.674

**Comment by brandonhellman** [comment]
The behavior with pressing the drop down and nothing happening has always seems to be tied with MTS using too much available ram or the system not having enough available for MTS (it shouldn't use that much, but edge cases exist).

Create new Chrome profile, your current one could be corrupted. If that doesn't fix the issue, you can install Chrome Canary and try it on there. If it works on the new Chrome profiles, then the old one was corrupted, if not and it works on Canary is probably something with Chrome. If it doesn't with Canary then we can move from there.

How much ram does your system have? Can you check to see if MTS is using a crazy amount of ram after an hour or so of use. The tab you have open is HIT Finder right?
