### ISSUE TITLE
Hit Finder Suggestion

### ISSUE THREAD

**Issue by Dissonan** [brandonhellman/mturk-suite#60]
I like the ability to use ctrl to select and manage multiple selections at the same time in the Hit Catcher. I think think that if it were possible, It would be very handy to be able to do the same in Hit Finder. For example, if there were multiple hits or requesters who I choose to block, I would be able to select each with ctrl and execute whichever command as a batch selection. It would then load them into a que to process them, where they would be added to the Block list separately if that necessary. I do not code and do know what is possible or worthwhile, but I thought it was an idea worth sharing. 

I've been using MTS for a short time now and it has been incredibly helpful; I'd like to say thank you for all the hard work

**Comment by alejandroshawqi** [comment]
The hit finder alarm should make the sound when new hits are available ; not with every ()ms 
it would be much better if that is applied 
I remember hit scraper used to alarm when new hits become available , that's much easier , useful and less annoying.

Thanks!
