### ISSUE TITLE
Feature Request: Show Colored Icons on Requester Project Listing

### ISSUE THREAD

**Issue by neocryptek** [brandonhellman/mturk-suite#61]
## Expected Behavior
It would be nice to show the same colored icons (profile, paid checkmark, etc) from
https://worker.mturk.com/projects on the requester page too:
https://worker.mturk.com/requesters/XXXX/projects
That way I can see if I've already done a task from that requester (and if it was paid, etc).

## Current Behavior
The icons are shown on the /projects page, but not the /requesters/XXXX/projects page.

## Possible Solution
Show the same icons on /requesters/XXXX/projects page

## Steps to Reproduce (for bugs)

1. Click on all HITs, notice that icons are displayed
2. Click on any requester, notice that icons are NOT displayed

## Context
Some requesters don't have MTurk rules setup properly to prevent multiples of them, but their instructions say don't do multiple of them. Having the icons show which ones I've already done would help prevent me from doing them multiple times and violating their rules which might get a rejection. Plus just consistency of UI it's odd to see the icons on one page and not on another that looks nearly identical.

## Your Environment
MTurk Suite 2.2.2 extension installed through store
Browser: Firefox 59.0.2 (64-bit) (MacOS 10.11.6)

**Comment by brandonhellman** [comment]
Included this in the 2.3 update coming this (5/26-5/27) weekend.

**Comment by neocryptek** [comment]
@Kadauchi I noticed in the latest update (2.3) that the per-HIT work-found checkmark seems to have disappeared. I see this line in the changelog: "HIT Tracker icons for no work found have been removed." Is it only supposed to go away when that HIT isn't found in Tracker? Right now I only see the per-requester checkmark when I've done work for that requester before (which works great on the requester project list page now thanks!).

Previously it was super useful to have the checkmark on each HIT to see if I've done a particular HIT before (ex: surveys where you can only do it once).

**Comment by brandonhellman** [comment]
The checkmark should appear next to the HIT Title when you completed a HIT with that same title same as before, just the no work found indicator was removed.

**Comment by neocryptek** [comment]
Hmm, updated to 2.3.4 on Firefox and disabled Tampermonkey completely (to avoid any script conflicts) and I still don't see the HIT title checkmarks. No errors in javascript console either. I see the HITs in HIT Tracker as paid.

@Kadauchi  Aha, okay I figured it out. The HIT-level checkmarks appear to be tied to the HIT export option setting. I always have the export turned off, but if I turn it on the checkmark shows up again. If I turn it back off, the checkmarks disappear too. 

Expected behavior?

**Comment by brandonhellman** [comment]
Definitely not. Should be easy to track down and fix though.

**Comment by neocryptek** [comment]
Oh one other small inconsistency I noticed was the new "block requester, block title, block HIT" (mentioned here https://github.com/Kadauchi/mturk-suite/issues/64#issuecomment-385455226 ) buttons on each HIT when you expand details only shows up on the all HITs search results, not the /requesters/XXXX/projects page.
