### ISSUE TITLE
Feature Request: Show Block/Include Shortcut on Search Results

### ISSUE THREAD

**Issue by neocryptek** [brandonhellman/mturk-suite#64]
Since the block list is used to filter out search results on the main MTurk search page, it would be nice if we could add HIT/Req to our block list directly from the search page. Currently we have to find the Ids, copy them, go over to MTS tab, create a new block, fill in the form by pasting in the Ids, etc. Repeat for each thing we want to block.

## Expected Behavior
Add extra buttons to existing popup
https://github.com/Kadauchi/mturk-suite/wiki/Scripts#requester-reviews

## Current Behavior
https://github.com/Kadauchi/mturk-suite/wiki/Scripts#requester-reviews

## Possible Solution
In the HIT Finder, when clicking the i information button for a result, it pops up a window with four buttons on it (Block HIT, Block Req, Include HIT, Include Req). It would be nice if those four buttons were included in the requester reviews popup on the main MTurk search results page shown here:
https://github.com/Kadauchi/mturk-suite/wiki/Scripts#requester-reviews

## Steps to Reproduce (for bugs)
1. Go to all HITs search result page in normal MTurk UI
2. Notice no way to quickly add search listings to block/include lists.

## Context
Using blocklist integration with main MTurk UI's search listings.

## Your Environment
MTurk Suite 2.2.3 extension installed through store
Browser: Firefox 59.0.2 (64-bit) (MacOS 10.11.6)

**Comment by brandonhellman** [comment]
I believe I'm going to have the new block buttons in the expandable like this.
![New Block Buttons](https://i.imgur.com/8Pt3SjF.png)

Can't have it with the requester reviews popup in case someone has `Requester Reviews` disabled but `Block List On MTurk` enabled.

This will be making this week's update.

**Comment by brandonhellman** [comment]
Coming in v2.3.0

**Comment by neocryptek** [comment]
That looks great; thanks!
