### ISSUE TITLE
Feature Request: Hit Finder: Ability to hide 'bad' requesters

### ISSUE THREAD

**Issue by rob-lindman** [brandonhellman/mturk-suite#65]
A button to toggle the following style would be useful:

```
tr.table-danger {
    display: none;
}

```

**Comment by brandonhellman** [comment]
You would do this with the minimum requester rating filter. "Bad" is anything below a `2.0`.

**Comment by rob-lindman** [comment]
Thanks. Figured this out on my own actually.
