### ISSUE TITLE
Feature Request: Wage Tracking

### ISSUE THREAD

**Issue by neocryptek** [brandonhellman/mturk-suite#66]
It would be nice if MTurk Suite HIT Tracker could use its database of HITs + pay and some timing information to calculate hourly wage. 

## Expected Behavior
When clicking on a day in the HIT Tracker's database, it should show average hourly wage for that day based on $ amount received, and time worked that day. I don't know if Amazon provides how long a HIT took in its API, else probably need some sort of helper script to watch for form submits on HIT pages to send time back to MTurk Suite database?

## Current Behavior
Only $ information is shown, as I assume timing information is not tracked or exposed by Amazon's APIs?

## Possible Solution
Add time tracking support (ex: watching submits) and use time + pay information to calculate hourly wage. Display with other daily stats in HIT Tracker database. Bonus points if it could be displayed per HIT, but per day would be a great start.

## Steps to Reproduce (for bugs)
1. Go to HIT Tracker
2. Click History tab
3. Click Daily Overview button
4. Notice that earnings per day is shown, but not $/hr wage

## Context
Would like to know how I'm doing overall on an hourly wage basis to know if I'm optimizing my time well or not on a given day.

## Your Environment
MTurk Suite 2.2.3 extension installed through store
Browser: Firefox 59.0.2 (64-bit) (MacOS 10.11.6)

**Comment by JrRandy** [comment]
Agreed, but I am not sure the duration the hit was worked is being captured in the database.  Hard to find a reliable $/hr script nowadays.

**Comment by brandonhellman** [comment]
This is something that will definitely be added.

@JrRandy The duration is not being captured currently. 

The simplest way to track hourly would be to just take the `time the hit was opened` / `reward` type deal. Pitfalls of this would be for people who work with multiple tabs opened and if you idle, both leading to a lower hourly. This is probably something that can be lived with and made more sophisticated in the future.

- Would be tied to each individual HIT. 
- Save time taken in seconds.
- Save hourly (mathed from time taken and reward).
- Display average in popover on MTurk.
- Display last submitted HIT's hourly on MTurk. 
- Display hourly averages in Tracker Overview for each requester and overall (daily, weekly, monthly).

Anything else?

**Comment by madhanprashanna** [comment]
Need a Script for wages

"starting HIT"  to  "Ending HIT"  /  "DATE " = "EARNINGS CALCULATOR"

Helpful for workers
