### ISSUE TITLE
Hit Catcher not alerting me

### ISSUE THREAD

**Issue by charliehaven** [brandonhellman/mturk-suite#67]
After catching lots of hits from a large batch, HC isn't saying "Hit Caught, NAME"

## Expected Behavior
HC isn't alerting me like it normally does.

## Current Behavior
After using HC to catch as much as I could from a batch and then switching it back to the normal handful that I catch on a daily basis, it's not alerting me. I've restarted my browser and it's still not working. I don't want to have to uninstall/reinstall MTS because then I lose all of my data.

## Context
See current behavior.

## Your Environment
* Version used: MTS v2.2.3
* Browser Name and version: Chrome 65
* Operating System and version (desktop or mobile): Mac OS Sierra

**Comment by Pascal666** [comment]
I'm having the same problem on v2.3.7 on Chrome 68 on Windows 7
