### ISSUE TITLE
Double weight to TurkerView in deciding which (yellow/red/green) requester icon to use

### ISSUE THREAD

**Issue by BestestMoose** [brandonhellman/mturk-suite#7]
Since if someone's filled out both the hourly and pay rate fields that's counting that (or those) reviewers twice for each TO review. 

...related, but I think the icon color should be more than just about pay.

**Comment by brandonhellman** [comment]
TurkerView gets double weighted because it is more accurate than both versions of Turkopticon and is considered the "main" requester review website for MTS. Pay is really the only thing that matters outside of rejections and blocks.
