### ISSUE TITLE
Hit tracker suggestion

### ISSUE THREAD

**Issue by Sir-Stroman** [brandonhellman/mturk-suite#70]
Hit tracker should be able to track bonuses, it would require user input but I think it would be a good feature.

**Comment by brandonhellman** [comment]
This is something I do have planned. I'd expect this to come in v2.4.0, that is when I plan on implementing a bunch of suggestions to Tracker.

**Comment by Sir-Stroman** [comment]
Awesome, great to hear! Thank you for your hard work.
