### ISSUE TITLE
Hit Finder gradually slowing down throughout the day

### ISSUE THREAD

**Issue by catnapped** [brandonhellman/mturk-suite#71]
Been seeing that the longer you run Hit Finder without refreshing the tab (or window) containing it that the poll times gradually start increasing throughout the day.  A 1 second (1000ms) timer starts creeping up to 2 seconds, then eventually 3 seconds, and ever higher (as evidenced by the clock display).  Running page sizes that are smaller (from say 50 to 35) staves off the issue for a little longer but eventually even it starts creeping up.

**Comment by brandonhellman** [comment]
I bet this is because of Tracker. The bigger Trackers's database, the worse it will be if I'm right. I've made some adjustments to Tracker which I think should stop this issue, but those changes were made to speed something else up, so I'll test Finder with them too and go from there.
