### ISSUE TITLE
Feature Request: HIT Catcher Browser Notifications

### ISSUE THREAD

**Issue by neocryptek** [brandonhellman/mturk-suite#72]
## Expected Behavior
It would be nice if HIT Catcher could emit notifications when it catches things (right now it only supports sounds, no popup browser notifications).

## Current Behavior
Currently only supports alerting the user via sounds

## Possible Solution
Add popup notifications to HIT Catcher

## Steps to Reproduce (for bugs)
1. Setup HIT Catcher to catch something, enable sounds
2. Wait for it to catch it
3. Notice that it plays a sound
4. Notice that there is no option to popup a notification

## Context
I usually keep my sound off, so browser notifications are the only way I get alerted

## Your Environment
MTurk Suite 2.2.3.1 extension installed through store
Browser: Firefox 60.0 (64-bit) (MacOS 10.11.6)

**Comment by Octopod2** [comment]
My sound is always on, but only about 1/2 of them are announced. An ongoing problem since the beginning.

**Comment by pequwzz** [comment]
No sound since last update
