### ISSUE TITLE
Auto-Accept Checker Script Won't Stop Running

### ISSUE THREAD

**Issue by Hiturunk** [brandonhellman/mturk-suite#73]
Auto-accept checker script continues to run whether checked or unchecked, with restarts of chrome, with restarts of MTS, etc.. I will attempt to investigate this issue further and provide a more workable means of reproduction with a vanilla copy ASAP.

## Expected Behavior
Unchecking the "auto-accept checker" in MTS options should stop the auto-accept script.

## Current Behavior
Whether toggled on or off, the auto-accept script continues to automatically check the "auto-accept" box on mturk.

## Possible Solution

Reinstalling the extension.

## Context
Causing auto-acceptance of single-take HITs on mturk, which is moderately annoying.

## Your Environment
MTS: 2.2.3.1
* Version used: 66.0.3359.181 (Official Build) (64-bit)
* Browser Name and version: Chrome
* Operating System: Windows 10, 64 BIT Build 16299

**Comment by lmhilly** [comment]
I reinstalled the extension, it does nothing. I disabled m-suite. still auto checking hits.

**Comment by Hiturunk** [comment]
So, it reproduced for you?

**Comment by lmhilly** [comment]
it still auto checks hits with mturk suite disabled in chrome...contacted Mturk....waiting for a reply

**Comment by brandonhellman** [comment]
This is the new MTurk default now. I'll be converting the Auto Accept Checker into an unchecker, but for now use this userscript.

https://greasyfork.org/en/scripts/368412-mturk-worker-auto-accept-unchecker

**Comment by brandonhellman** [comment]
This [commit](https://github.com/Kadauchi/mturk-suite/commit/35e1cd61330080920a0db7a900f5be4fa9412f6c) changes the checker into an unchecker, will make it out in the build being pushed with weekend.

**Comment by Hiturunk** [comment]
Awesome, thanks!
