### ISSUE TITLE
Auto accept-I do not need this option.Check box not working, it accepts automatically , even i " uncheck " the box, Please solve this issue

### ISSUE THREAD

**Issue by konnadipaiyan** [brandonhellman/mturk-suite#74]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by rater9** [comment]
This bug is very annoying. Hope to see resolution soon. It is definitely costing time while working. Thanks for all you do!!!

**Comment by JustJenagain** [comment]
This is happening to me as well....frustrating. I kept thinking amazon changed a setting until I checked here...I use google chrome canary ver 68.0.3440.0 (Official Build) (64-bit). laptop win 10 home insider's edition ver 1803 build 17134.81

**Comment by JrRandy** [comment]
This is now the new behavior of mturk, nothing related to MTS.  There has been a script created to uncheck the box to over ride this new setting.  You can search /r/mturk to find it.

**Comment by brandonhellman** [comment]
This is an MTurk issue, not an MTS issue.
See: https://github.com/Kadauchi/mturk-suite/issues/73#issuecomment-391792449
