### ISSUE TITLE
What these prefix  colours before every requester , indicates ? (red, yelllow . blue, maroon) 

### ISSUE THREAD

**Issue by konnadipaiyan** [brandonhellman/mturk-suite#75]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by brandonhellman** [comment]
Covered in the wiki [here](https://github.com/Kadauchi/mturk-suite/wiki/Scripts#requester-reviews).
