### ISSUE TITLE
Week range expired

### ISSUE THREAD

**Issue by JrRandy** [brandonhellman/mturk-suite#76]
Ran out of week ranges provided in last version causing the Projected This Week and Projected This Month to fail.

**Comment by brandonhellman** [comment]
Fixed with this [commit](https://github.com/Kadauchi/mturk-suite/commit/f7474db26a8d4b898175805f2c3d1e382a7a8600). Didn't get enough testing done yesterday to push a build, working through it now.

**Comment by JrRandy** [comment]
Thanks @Kadauchi If you need some testing, I am always happy to lend a hand  :)
