### ISSUE TITLE
Auto accept is on even when disabled in the setting

### ISSUE THREAD

**Issue by dgrochester55** [brandonhellman/mturk-suite#77]
I usually like to keep auto accept off unless working on a batch.   I have noticed over the last couple of days that even when unchecked in the options, my next hit is auto accepting resulting in me having duplicate surveys in my queue that i do not know about.  I have verified that it is uncheck, and also closed out multiple times before trying again.

**Comment by brandonhellman** [comment]
This is an MTurk issue, not an MTS issue.
https://github.com/Kadauchi/mturk-suite/issues/74#issuecomment-392030769
https://github.com/Kadauchi/mturk-suite/issues/73#issuecomment-391792449
