### ISSUE TITLE
Feature Request for Panda Crazy integration.

### ISSUE THREAD

**Issue by LLL-GitHub** [brandonhellman/mturk-suite#78]
![hit finder request](https://user-images.githubusercontent.com/36159244/40589634-2d497b0c-61b6-11e8-98cf-8e7de880e61d.png)

Do you have any plans to add any options for Panda Crazy. I would like to suggest the above idea.

**Comment by brandonhellman** [comment]
Nope.  No plans to ever have stuff for other userscripts. That time would be better spent making Catcher better.
