### ISSUE TITLE
Is there a way to remove the new 'share' option from Hitfinder?

### ISSUE THREAD

**Issue by TurkEmup** [brandonhellman/mturk-suite#79]
I'm on chrome with the newest update to MTS. The new share button on Hitfinder makes it super bulky and  slows down the time it takes to see the hit title and select the hit. The page also looks awkward now and goes slow. Is there any way to remove it?

Also, the page keeps jumping up and down which makes it tough.

**Comment by brandonhellman** [comment]
The share button isn't new. Looks like a issue with the display settings in Finder.
