### ISSUE TITLE
Hit tracker not tracking

### ISSUE THREAD

**Issue by JrRandy** [brandonhellman/mturk-suite#8]
Hi there.  Sometime yesterday, my hit tracker stopped functioning properly.  It no longer tracks automatically (ie: amount earned does not increase with each submission, returned hits are no longer tracked etc).  

I attempted to disable and re-enable, and also uninstall and re-install to no avail.  Was working fine until yesterday.

**Comment by brandonhellman** [comment]
Fix will be included in v2.1.4
