### ISSUE TITLE
 Auto Sync not working / earnings are not working or updating

### ISSUE THREAD

**Issue by lmhilly** [brandonhellman/mturk-suite#80]
earnings are not working on Mturk even after syncing 

auto sync is grayed out, not able to put check mark in the box in options

**Comment by brandonhellman** [comment]
Not currently implemented as the tooltip on that checkbox says.

**Comment by kattie0002** [comment]
Will not syncing , does nothing, it seems to just no even start when you click on the button to make it like update, your earnings and the hits that you have done ,
