### ISSUE TITLE
earnings not being updated

### ISSUE THREAD

**Issue by xkdhc3i** [brandonhellman/mturk-suite#81]
I just applied the latest update and did a few hits, earnings stays at zero, dashboard shows correct amounts.

## Your Environment
chrome Version 66.0.3359.181
windows 10

**Comment by brandonhellman** [comment]
Looking into it now.

**Comment by JrRandy** [comment]
Same, the "Live Update" appears to have stopped functioning in the new version.  Still displays the amount I had just before the update at the top of the pages, even if I sync the day to update the dashboard.

**Comment by Rainingcatsnstuff** [comment]
I'm also having this issue, since last night.

**Comment by brandonhellman** [comment]
Looks like the function for this is only running when the extension starts, so after an update, restart or whatever.

**Comment by JrRandy** [comment]
I disabled and re-enabled the extension, and it updated the "LIve Update" number for my current stats, however did not update as I completed additional hits.
