### ISSUE TITLE
Suggestion or Question (SIAP) 

### ISSUE THREAD

**Issue by RIPtaDAcomp** [brandonhellman/mturk-suite#82]
I am apoligize if its been discussed but I've only been turking for a couple months. There are several requesters that I have blocked and the HIT Finder has a max of 100 HITs so I can only display about 30 some HIT's,  any suggestions? Am I doing something wrong?

**Comment by brandonhellman** [comment]
You aren't doing anything wrong, this is normal and expected. The 100 HIT limit is the max allowed by MTurk.

**Comment by RIPtaDAcomp** [comment]
Ah I see, thanks!
