### ISSUE TITLE
Since update Catch Once/Multiple no longer shows up from the there are no more of these hits page

### ISSUE THREAD

**Issue by Rainingcatsnstuff** [brandonhellman/mturk-suite#83]
Hey. Since the update I've had an issue and I wondered if there was something I needed to change in the settings? 
Prior to the update when I would click on a hit and there were no more it would take me to  Mturk's "There are no more of these HITs available" page and in the box would be the option to Catch once or Multiple times. 
But now the option isn't there. Having that option really sped up the time everything took. Now I have to click out of that page, go back to hit finder, find that exact hit, go down and right click to get the option to catch once or multiple times. I do catch straight from the finder sometimes, but having it right on the no more hits page was super useful. Is there a setting I need to check?

**Comment by perkinsj882** [comment]
I'm having the same issue.

**Comment by brandonhellman** [comment]
I'll check it out now.

**Comment by perkinsj882** [comment]
Thanks! I couldn't survive with this tool.

**Comment by Rainingcatsnstuff** [comment]
Thank you!
