### ISSUE TITLE
No button for HIT catcher

### ISSUE THREAD

**Issue by jbturker** [brandonhellman/mturk-suite#84]
After clicking on a HIT in HIT finder that has already been accepted and is no longer available the buttons to add to HIT catcher is not there. I've tried just about everything I can think of. Am I the only one having this issue?
## Expected Behavior

After clicking on a no longer available HIT the buttons should appear to add that HIT to HIT catcher

## Current Behavior

The buttons do not appear.

## Possible Solution

I noticed this bug after the new update was installed. I'm terrible at scripts so I couldn't begin to tell you why. I do believe it is directly related to the update though.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I was trying to add HITs to HIT catcher.

## Your Environment

* Version used: 2.3
* Browser Name and version: Google Chrome V - 66.0.3359.181
* Operating System and version (desktop or mobile): Windows 10 Home - Desktop.

**Comment by brandonhellman** [comment]
Fixed in 2.3.1. https://github.com/Kadauchi/mturk-suite/issues/83
