### ISSUE TITLE
'Once' and 'PandA' buttons missing from There are no more of these HITs available since update on 5/27

### ISSUE THREAD

**Issue by beeeekman** [brandonhellman/mturk-suite#86]
The buttons that would add a HIT to the Catcher are now missing from the There are no more of these HITs available screen. These were a tremendous time saver and since the update the do not show up.

## Expected Behavior
Once and PandA buttons should be visible on the 'There are no more of these HITs available' screen that add groupID's to the HIT catcher.

## Current Behavior
None. They are gone.

## Possible Solution
I am a novice coder at best so I have no idea. I just know that they were one of the best features and helped make me more money.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
Following links from TurkerHub, MTS Finder itself, and the native mturk interface yield this result. There was a recent update (5/27/18) and since then this issue has been occurring. I like the other changes, though, btw.

## Your Environment
version 2.3 Sunday, May 27, 2018
Windows 10
Chrome
Have tried with Tampermonkey both disabled and enabled. Same result so I don't think there are any interfering scripts.

**Comment by TurkWarrior** [comment]
I am also having this same issue after the latest update with all the same parameters (Windows 10, Chrome, Mturk Suite Version 2.3.1). Not sure if we're all supposed to report this so helpers can see it's a large issue, or if we just let one person post and wait for someone with a solution to come by.

**Comment by brandonhellman** [comment]
@TurkWarrior thought I had it fixed with 2.3.1, I'll go back and check it out.

**Comment by brandonhellman** [comment]
@TurkWarrior I cannot replicate this issue in 2.3.1.

**Comment by Octopod2** [comment]
2/6, this problem has returned, started yesterday.
