### ISSUE TITLE
Sorry , it is BLOCKLIST, not blacklist , in previous issue i told

### ISSUE THREAD

**Issue by konnadipaiyan** [brandonhellman/mturk-suite#88]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):

Edit: (Questions from before)
I wish to know what is black list ? Is that the requesters put temporary block on me ? or those are the requester I do not want to work , that i decide and mark ?

**Comment by brandonhellman** [comment]
The Block List is for requesters or HITs that you don't want to have appear on MTurk anymore. Useful for block requesters that are known to reject valid work, pay low or whatever reason you want.
