### ISSUE TITLE
Panda and once button still on vacation

### ISSUE THREAD

**Issue by Zamia1974** [brandonhellman/mturk-suite#89]
I have version 2.3.1 but the panda and once buttons did not return from vacation as expected 

* Browser Chrome version 66.0.3359.181
* Operating System Win 10

**Comment by skhatesme** [comment]
I'm having the same issue. No Once or Panda buttons show when I click on a hit that is no longer available.

**Comment by brandonhellman** [comment]
Fixed https://github.com/Kadauchi/mturk-suite/commit/810350a91c5f3994f2de51dd878dd2565b2d1216

Let me know if this still happens after you get updated to 2.3.3.
