### ISSUE TITLE
Where's the chick that says you are logged out?

### ISSUE THREAD

**Issue by AlienGit** [brandonhellman/mturk-suite#9]
Where's the chick that says you are logged out?

New site randomly logs you out... missed an important hit yesterday, realized I'm not getting told I was logged out anymore.

Bringing that back?

**Comment by brandonhellman** [comment]
It never left. Try rebooting your browser, text to speech will sometimes fail and get stuck preventing any more text to speech from happening.

**Comment by AlienGit** [comment]
Nah, I have it running on 4 computers... occam's razor says, it's the extension.

Conflict with something else? T2S is up, running and audible.

Win 7 Ult SP1 
Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by brandonhellman** [comment]
Which browser and browser version are you using?

**Comment by AlienGit** [comment]
Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by JrRandy** [comment]
I have the same issue, but just recently started using the extension so didn't know it used to have this feature :)

**Comment by AlienGit** [comment]
<html>
<head>
<script>
var synth = window.speechSynthesis;
var ttsStart = function () {
		console.log("starting");
		var myText = document.getElementById("myTextArea").value;
		
		var utterThis = new SpeechSynthesisUtterance(myText);
		synth.speak(utterThis);

		utterThis.onstart = function(event) {
		console.log('We have started uttering this speech: ' + event.utterance.text);
		}
		utterThis.onend = function (event) {
		console.log("[Utterance ended]");
		}
	}
var ttsCancel = function () {
	window.speechSynthesis.cancel();
}
</script>
</head>
<body>
<textarea id="myTextArea" cols="50" rows="15">
Up until about the end of 2016, or maybe in early 2017, Windows Chrome TTS functionality stopped working the way it used to. 
If you will notice, it stops around 200 or 300 characters even though the documentation says 32,768 characters is the 
maximum limit. On my PC browser, the text will have stopped being read before this point. And you would need to hit 
the Cancel button to reset the utterance because it is just hanging for no apparent reason. Longer passages, just under 
1400 characters, do not read aloud at all. Please fix, please because I love TTS so much. Thanks!</textarea><br />
<button id="start" onclick="ttsStart()">Start</button> <button id="cancel" onclick="ttsCancel()">Cancel</button> 

</body>
</html>


This file works BTW.

**Comment by AlienGit** [comment]
`<html>
<head>
<script>
var synth = window.speechSynthesis;
var ttsStart = function () {
		console.log("starting");
		var myText = document.getElementById("myTextArea").value;
		
		var utterThis = new SpeechSynthesisUtterance(myText);
		synth.speak(utterThis);

		utterThis.onstart = function(event) {
		console.log('We have started uttering this speech: ' + event.utterance.text);
		}
		utterThis.onend = function (event) {
		console.log("[Utterance ended]");
		}
	}
var ttsCancel = function () {
	window.speechSynthesis.cancel();
}
</script>
</head>
<body>
<textarea id="myTextArea" cols="50" rows="15">
Up until about the end of 2016, or maybe in early 2017, Windows Chrome TTS functionality stopped working the way it used to. 
If you will notice, it stops around 200 or 300 characters even though the documentation says 32,768 characters is the 
maximum limit. On my PC browser, the text will have stopped being read before this point. And you would need to hit 
the Cancel button to reset the utterance because it is just hanging for no apparent reason. Longer passages, just under 
1400 characters, do not read aloud at all. Please fix, please because I love TTS so much. Thanks!</textarea><br />
<button id="start" onclick="ttsStart()">Start</button> <button id="cancel" onclick="ttsCancel()">Cancel</button> 

</body>
</html>`

This file works BTW

**Comment by AlienGit** [comment]
[TTS_test - Copy.txt](https://github.com/Kadauchi/mturk-suite/files/1665327/TTS_test.-.Copy.txt)

This file works BTW.

**Comment by AlienGit** [comment]
@JrRandy, try that file I posted, save it as a HTML, drag into chrome and see if she speaks.

**Comment by JrRandy** [comment]
When I open it and click "Start" it reads the full dialogue.  With a dude, not a chick if that means anything lol

**Comment by AlienGit** [comment]
Haha, yeah, it's either Bob or David, and not Anna  =)

But we know TTS works  =)

**Comment by JrRandy** [comment]
yeah, I get the "Included hit blah blah blah has been found" without issue as well.  Just no notification of the logout.  I just notice it stops updating the screen, pop to the MTurk page, and see that I need to log in.

**Comment by brandonhellman** [comment]
Open the console on HIT Catcher (ctrl+shift+j) and then use this `textToSpeech('phrase you want to say here')`. Does it speak?

**Comment by JrRandy** [comment]
@Kadauchi - Yes, that works fine

**Comment by AlienGit** [comment]
@Kadauchi Yes, works for me too.

**Comment by AlienGit** [comment]
FWIW, it doesn't announce, when you manually log out also.

**Comment by AlienGit** [comment]
@Kadauchi - still working on this?

**Comment by brandonhellman** [comment]
Yep, still on the todo list.

**Comment by AlienGit** [comment]
Ok, thanks!
