### ISSUE TITLE
Unable to find the HIT 

### ISSUE THREAD

**Issue by princeJoelMathew** [brandonhellman/mturk-suite#90]
Unable to find the HIT after clicking find HIT.. Nothing showing

![snap 2018-05-28 at 22 48 56](https://user-images.githubusercontent.com/35998240/40624299-5f82cf10-62c9-11e8-89aa-1bf2b6d5e94c.jpg)

* Version used: 2.3.2
* Browser Name and version: Firefox Nightly & 62.0a1 (2018-05-28)(64 Bit)
* Operating System and version (desktop or mobile): Laptop Windows 10

**Comment by brandonhellman** [comment]
What are your settings? Also open the console `Ctrl+Shift+J` and see if there are any errors.

**Comment by princeJoelMathew** [comment]
please refer the error message for your information..
![snap 2018-05-28 at 23 07 53](https://user-images.githubusercontent.com/35998240/40624756-07fa8cc6-62cc-11e8-9b76-11250942b2c2.jpg)

Error message 


[Show/hide message details.] Promise resolved after context unloaded
common.js:4
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onsubmit attribute on INPUT element. 1
Use of Mutation Events is deprecated. Use MutationObserver instead. rs=AHGWq9AhozItOs1Nw2dlqKpAszYC4-Kw5A line 126 > eval:328:77
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
[Show/hide message details.] Promise resolved while context is inactive
common.js:4
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element. postmessageRelay
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element. load
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element. frame2
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element. frame2
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element. frame
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element.
widget
Content Security Policy: Couldn’t parse invalid host 'report-sample'
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Couldn’t parse invalid host 'report-sample'
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Couldn’t parse invalid host 'report-sample'
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element. 3
[Show/hide message details.] No matching message handler for the given recipient.
MessageChannel.jsm:914
[Show/hide message details.] b.tab is undefined
MessageChannel.jsm:964
[Show/hide message details.] Promise resolved while context is inactive
common.js:4
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://play.google.com/log?format=json&u=1&authuser=1. (Reason: CORS request did not succeed).
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onsubmit attribute on INPUT element. 3
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element.
3
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element.
widget
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Use of Mutation Events is deprecated. Use MutationObserver instead. rs=AHGWq9D-OJ5v74Lv5cSSfMs0_eW1AYuKGQ line 126 > eval:328:77
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element. postmessageRelay
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element. load
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element. frame2
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element. frame2
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element. frame
[Show/hide message details.] TypeError: window.opener is null eval line 3 > Function:661:21
The character encoding of a framed document was not declared. The document may appear different if viewed without the document framing it. hscv
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onfocusin attribute on DIV element. hscv
[Show/hide message details.] TypeError: window.opener is null eval line 3 > Function:661:21
Attempt to set a forbidden header was denied: Connection
908488570-lcs_client_bin.js:193:386
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ eval line 3 > Function:60:1
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/You%20have%20less%20than%201%20hour%20left%20-%20Laura.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/You%20have%20less%20than%201%20hour%20left%20-%20Paul.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/Alarm%2060%20minutes%20left.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/You%20have%20less%20than%2030%20minutes%20left%20-%20laura.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/You%20have%20less%20than%2030%20minutes%20left%20-%20Paul.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/Alarm%2030%20minutes%20left.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/You%20have%20less%20than%2020%20minutes%20left%20-%20laura.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/You%20have%20less%20than%2020%20minutes%20left%20-%20Paul.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/Alarm%2020%20minutes%20left.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/You%20have%20less%20than%2010%20minutes%20left%20-%20Laura.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/You%20have%20less%20than%2010%20minutes%20left%20-%20Paul.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/Alarm%2010%20minutes%20left.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/You%20have%20less%20than%205%20minutes%20left%20-%20Laura.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/You%20have%20less%20than%205%20minutes%20left%20-%20Paul.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/Alarm%205%20minutes%20left.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/You%20have%20less%20than%201%20minute%20left%20-%20Laura.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/You%20have%20less%20than%201%20minute%20left%20-%20Paul.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/Alarm%201%20minute%20left.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/You%20have%20less%20than%2030%20seconds%20left%20-%20Laura.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/You%20have%20less%20than%2030%20seconds%20left%20-%20Paul.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/Alarm%2030%20seconds%20left.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/This%20is%20just%20a%20test%20of%20this%20warning%20system%20-%20Laura.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Loading mixed (insecure) display content “http://www.allbyjohn.com/sounds/This%20is%20just%20a%20test%20of%20this%20warning%20system%20-%20Paul.mp3” on a secure page[Learn More] 38XPGNCKHTFM1GINV6OGRWHANHX4V8
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead eval:3:75
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead eval line 2 > eval:3:75
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fls-na.amazon.com/1/batch/1/OP/mkt=aiwnacsm:285-8371979-8079558:4BXHNHIYVHQ79SUSFUAR:worker.mturk.com$uedata=s:%2Fuedata%2F285-8371979-8079558%2F%3Ful%26v%3Da02%26id%3D4BXHNHIYVHQ79SUSFUAR%26ctb%3D1%26m%3D1%26sc%3D4BXHNHIYVHQ79SUSFUAR%26pc%3D6977%26tc%3D-1545%26ul%3D6977%26t%3D1527528981491%26csmtags%3D%7C%7C:6977. (Reason: CORS request did not succeed).
[Show/hide message details.] Promise resolved while context is inactive
common.js:4
Error: WebExtension context not found! ExtensionParent.jsm:1009:13
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ eval line 3 > Function:60:1
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
In add-on {dd19b0aa-6eee-4a10-a6bc-361a163f7821}, attempting to use listener "notifications.onButtonClicked", which is unimplemented. ExtensionParent.jsm:995:35
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
[Show/hide message details.] No matching message handler for the given recipient. MessageChannel.jsm:914
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fls-na.amazon.com/1/batch/1/OP/mkt=aiwnacsm:285-8371979-8079558:4DJQKBLVPMZ08A4GGAT8:worker.mturk.com$uedata=s:%2Fuedata%2F285-8371979-8079558%2F%3Ful%26v%3Da02%26id%3D4DJQKBLVPMZ08A4GGAT8%26ctb%3D1%26m%3D1%26sc%3D4DJQKBLVPMZ08A4GGAT8%26pc%3D15808%26tc%3D-2325%26ul%3D15808%26t%3D1527528999620%26csmtags%3D%7C%7C:15808. (Reason: CORS request did not succeed).
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Handler function threw an exception: TypeError: this.transport is null
Stack: send@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1476:5
addSecurityInfo@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/network-event.js:391:5
NetworkResponseListener.prototype._getSecurityInfo<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/webconsole/network-monitor.js:519:5
exports.makeInfallible/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
onStartRequest@resource://devtools/shared/base-loader.js -> resource://devtools/shared/webconsole/network-monitor.js:439:5
Line: 1476, column: 5 ThreadSafeDevToolsUtils.js:88:5
TypeError: this.transport is null[Learn More] main.js:1476:5
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Handler function threw an exception: TypeError: this.transport is null
Stack: send@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1476:5
addSecurityInfo@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/network-event.js:391:5
NetworkResponseListener.prototype._getSecurityInfo<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/webconsole/network-monitor.js:519:5
exports.makeInfallible/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
onStartRequest@resource://devtools/shared/base-loader.js -> resource://devtools/shared/webconsole/network-monitor.js:439:5
Line: 1476, column: 5 ThreadSafeDevToolsUtils.js:88:5
TypeError: this.transport is null[Learn More] main.js:1476:5
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Handler function threw an exception: TypeError: this.transport is null
Stack: send@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1476:5
addSecurityInfo@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/network-event.js:391:5
NetworkResponseListener.prototype._getSecurityInfo<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/webconsole/network-monitor.js:519:5
exports.makeInfallible/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
onStartRequest@resource://devtools/shared/base-loader.js -> resource://devtools/shared/webconsole/network-monitor.js:439:5
Line: 1476, column: 5 ThreadSafeDevToolsUtils.js:88:5
TypeError: this.transport is null[Learn More] main.js:1476:5
Error: Type error for parameter options (Property "buttons" is unsupported by Firefox) for notifications.create. hit-finder.js:397:5
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Handler function threw an exception: TypeError: this.transport is null
Stack: send@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1476:5
addSecurityInfo@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/network-event.js:391:5
NetworkResponseListener.prototype._getSecurityInfo<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/webconsole/network-monitor.js:519:5
exports.makeInfallible/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
onStartRequest@resource://devtools/shared/base-loader.js -> resource://devtools/shared/webconsole/network-monitor.js:439:5
Line: 1476, column: 5 ThreadSafeDevToolsUtils.js:88:5
TypeError: this.transport is null[Learn More] main.js:1476:5
Time to fetch HITs: 361 userscript.html:24:1380960
[SW] on message <unavailable> js/lib/push_worker.js:85:3
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Time to fetch HITs: 355 userscript.html:24:1380960
[SW] on message <unavailable> js/lib/push_worker.js:85:3
Time to fetch HITs: 361 userscript.html:24:1380960
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Time to fetch HITs: 432 userscript.html:24:1380960
Time to fetch TO: 1365 userscript.html:24:1401975
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Time to fetch HITs: 560 userscript.html:24:1380960
[SW] on message <unavailable> js/lib/push_worker.js:85:3
Time to fetch HITs: 341 userscript.html:24:1380960
[SW] on message <unavailable> js/lib/push_worker.js:85:3
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Time to fetch HITs: 363 userscript.html:24:1380960
Time to fetch TO: 789 userscript.html:24:1401975
Error: WebExtension context not found!
ExtensionParent.jsm:1009:13
In add-on {dd19b0aa-6eee-4a10-a6bc-361a163f7821}, attempting to use listener "notifications.onButtonClicked", which is unimplemented. ExtensionParent.jsm:995:35
Time to fetch HITs: 352 userscript.html:24:1380960
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
retrieveMessage/<
moz-extension://4c2b3d2d-76aa-40b3-b6de-254c1868a973/userscript.html:661:21
g</< eval:2:479 ja/c[d] eval line 1 > Function:52:483
Time to fetch HITs: 349 userscript.html:24:1380960
Time to fetch TO: 296 userscript.html:24:1401975
Error: Type error for parameter options (Property "buttons" is unsupported by Firefox) for notifications.create. hit-finder.js:397:5
Time to fetch HITs: 378 userscript.html:24:1380960
[SW] on message <unavailable> js/lib/push_worker.js:85:3
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
[SW] on message <unavailable> js/lib/push_worker.js:85:3
Time to fetch HITs: 378 userscript.html:24:1380960
Time to fetch HITs: 341 userscript.html:24:1380960
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Time to fetch HITs: 342 userscript.html:24:1380960
Time to fetch TO: 770 userscript.html:24:1401975
Time to fetch HITs: 367 userscript.html:24:1380960
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
[SW] on message <unavailable> js/lib/push_worker.js:85:3
Time to fetch HITs: 354 userscript.html:24:1380960
[SW] on message <unavailable> js/lib/push_worker.js:85:3
Time to fetch HITs: 360 userscript.html:24:1380960
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Time to fetch HITs: 361 userscript.html:24:1380960
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Time to fetch HITs: 357 userscript.html:24:1380960
Time to fetch HITs: 363 userscript.html:24:1380960
[SW] on message <unavailable> js/lib/push_worker.js:85:3
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
[SW] on message <unavailable> js/lib/push_worker.js:85:3
Time to fetch HITs: 355 userscript.html:24:1380960
Time to fetch HITs: 382 userscript.html:24:1380960
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Time to fetch HITs: 343 userscript.html:24:1380960
Time to fetch HITs: 366 userscript.html:24:1380960
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
[SW] on message <unavailable> js/lib/push_worker.js:85:3
Time to fetch HITs: 355 userscript.html:24:1380960
[SW] on message <unavailable> js/lib/push_worker.js:85:3
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Time to fetch HITs: 375 userscript.html:24:1380960
Time to fetch TO: 751 userscript.html:24:1401975
Time to fetch HITs: 370 userscript.html:24:1380960
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Time to fetch HITs: 453 userscript.html:24:1380960
[SW] on message <unavailable> js/lib/push_worker.js:85:3
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
[SW] on message <unavailable> js/lib/push_worker.js:85:3
Time to fetch HITs: 356 userscript.html:24:1380960
Time to fetch TO: 752 userscript.html:24:1401975
Time to fetch HITs: 362 userscript.html:24:1380960
Time to fetch TO: 265 userscript.html:24:1401975
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Time to fetch HITs: 368 userscript.html:24:1380960
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Time to fetch HITs: 2812 userscript.html:24:1380960
Time to fetch TO: 754 userscript.html:24:1401975
[SW] on message <unavailable> js/lib/push_worker.js:85:3
[SW] on message <unavailable> js/lib/push_worker.js:85:3
Time to fetch HITs: 414 userscript.html:24:1380960
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Time to fetch HITs: 477 userscript.html:24:1380960
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Time to fetch HITs: 384 userscript.html:24:1380960
Time to fetch TO: 763 userscript.html:24:1401975
Time to fetch HITs: 352 userscript.html:24:1380960
[SW] on message <unavailable> js/lib/push_worker.js:85:3
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
[SW] on message <unavailable> js/lib/push_worker.js:85:3
Time to fetch HITs: 365 userscript.html:24:1380960
Time to fetch HITs: 366 userscript.html:24:1380960
[Show/hide message details.] TypeError: window.opener is null
eval line 3 > Function:661:21
Time to fetch HITs: 353 userscript.html:24:1380960
Time to fetch HITs: 365 userscript.html:24:1380960
[Show/hide message details.] TypeError: window.opener is null eval line 3 > Function:661:21
[SW] on message <unavailable> js/lib/push_worker.js:85:3
Time to fetch HITs: 438 userscript.html:24:1380960
[SW] on message <unavailable> js/lib/push_worker.js:85:3
[Show/hide message details.] TypeError: window.opener is null eval line 3 > Function:661:21
Time to fetch HITs: 340 userscript.html:24:1380960
Time to fetch HITs: 400 userscript.html:24:1380960
[Show/hide message details.] TypeError: window.opener is null eval line 3 > Function:661:21
Time to fetch HITs: 339 userscript.html:24:1380960
[SW] on message <unavailable> js/lib/push_worker.js:85:3
[Show/hide message details.] TypeError: window.opener is null eval line 3 > Function:661:21
Time to fetch HITs: 350 userscript.html:24:1380960
[SW] on message <unavailable> js/lib/push_worker.js:85:3
Time to fetch HITs: 356 userscript.html:24:1380960
[Show/hide message details.] TypeError: window.opener is null eval line 3 > Function:661:21
Time to fetch HITs: 349 userscript.html:24:1380960
Time to fetch HITs: 397 userscript.html:24:1380960

**Comment by brandonhellman** [comment]
Oh Firefox, F12 and do the same, sorry.

**Comment by princeJoelMathew** [comment]
Kindly for your information

![snap 2018-05-28 at 23 15 55](https://user-images.githubusercontent.com/35998240/40624966-36d6914c-62cd-11e8-9c76-0c7f9ba6740e.jpg)

**Comment by brandonhellman** [comment]
Click the Console tab.

**Comment by princeJoelMathew** [comment]
![snap 2018-05-28 at 23 18 15](https://user-images.githubusercontent.com/35998240/40624993-6a8ebdc0-62cd-11e8-8f91-b7bd54b68472.jpg)

**Comment by princeJoelMathew** [comment]
hi, Please suggest way to forward .. Still I am facing issues Please do the needful..

**Comment by brandonhellman** [comment]
Update to version 2.3.3.

**Comment by princeJoelMathew** [comment]
Thanks for your great support.. Now HIT finder issues got resolved after updating the new version 2.3.3
