### ISSUE TITLE
5 Issues/Suggestions

### ISSUE THREAD

**Issue by Leviathon2** [brandonhellman/mturk-suite#92]
1) Minimum Requester Rating in Hit Finder confuses me. Can you explain how it works?

After the update, I got a ton of red showing up that would've normally been filtered out before the update. For example, I have it set to 2.5. However, Chaim Fried showed up. Current TO ratings:

Pay: 1.5
Fast: 5
Communication: 0
Fair: 5

My speed is 2100 ms (no Hit Catcher on...I don't use that, I use PC). 

2) I still would like the option to add text to a hit before I export it to mturkcrowd. That way I can easily put in the hourly instead of editing the post after making it. Using BBCode & copy/pasting that & then the hourly is what I've been doing for the time being, but it definitely takes more time.

3) When selecting show block list on an mturk page, nothing happens. 

4) I only need BBCode & MTurkcrowd to show up in "Share Hit" popup on Hit Finder. Perhaps there will be a way to edit that so only the choices you use will show up or give the ability to remove it if you don't want to use it?

5) Request: An option in MTS options to disable Hit Catcher (remove it from drop down list) would be nice. Basically, if unchecked Hit Catcher wouldn't show up on drop down list. It would just be HF, Hit Tracker, & MTS options.

**Comment by brandonhellman** [comment]
1. Chaim shouldn't make it on the recent section, may have slipped through to logged section before the ratings were retrieved. I'll have to add something for them to be plucked out after the fact.

2. This is currently how it works.

3. Are there any errors in the console `F12 => Console tab`?

4. With the new way the options are being done, I can probably switch those options from radios to checkboxes and have it do logic based on that.

5. Going to say no for now. Maybe if I'm fiddling with stuff in that area.

**Comment by Leviathon2** [comment]
1) There is definitely something wrong with TO. Idk if that's from the TO websites or not though. Since the update, TOs are not showing up. I can reset it, but that only works for a limited time. Also, no TO rankings are being filtered out now.

3) storage.js:17 "hitExporter" did not resolve because it is disabled.
Enabled.Promise @ storage.js:17

**Comment by brandonhellman** [comment]
2. You disabled HIT Exporter in the options if you're getting that error.

Walk me through step by step for this issue.

Both of these posts were directly from MTS with text included.
https://www.mturkcrowd.com/posts/1250637/
https://www.mturkcrowd.com/posts/1250638/

**Comment by Leviathon2** [comment]
2) I did disable that. Doesn't make any difference though. I enabled it & still doesn't work.
When selecting show block list on an mturk page, nothing happens.
For example, https://worker.mturk.com/projects/?page_number=2#
On that page is says "show blocked (20)". There is a plus sign next to that message. When I click the plus sign, nothing happens.

**Comment by Leviathon2** [comment]
Also, I know I already mentioned it but HF is definitely not screening out TO.

**Comment by brandonhellman** [comment]
Are you getting console log errors when clicking? I need more than "not working" at this point. Each work on the latest Chrome and Firefox for me.

I'm closing this. Each feature/issue needs to be separated or else this is going to become a giant mess.

**Comment by Leviathon2** [comment]
I know this is closed, but just wanted to update you about the block issue. It does work, but not when you click on the plus sign. That's what I was doing. I didn't think that moving to the words themselves would have a different outcome. So, that's what happened. If you click just on the cross icon, it should do nothing
