### ISSUE TITLE
Two broken features on Firefox with newest update

### ISSUE THREAD

**Issue by conanismyidol** [brandonhellman/mturk-suite#93]
I'm having trouble with a few things since the latest update. The "Input worker ID" when right-clicking does not paste anything anymore. Also, there is no check mark next to specific titles of HITs that were completed, only for specific requesters. IE only showing up next to a requesters name if I've completed a HIT by them, but no check marks appearing next to the titles of HITs, even when I know I've completed them.

This is happening on Firefox, but appears to be working in Chrome. Currently using Firefox 61.0b8 on Windows 10.

Thanks so much for all you do on this extension. I don't know what I'd do without it!

**Comment by brandonhellman** [comment]
I'll check it out.

**Comment by brandonhellman** [comment]
Since you're on a Firefox beta channel, can you open the console and see if there are any errors? I;m getting check marks next to both requester name and hit title (if I've actually done a HIT with that title). It wouldn't be too uncommon to have check marks next to a requester and not a title.
