### ISSUE TITLE
Export not working for me

### ISSUE THREAD

**Issue by mmbrown2000** [brandonhellman/mturk-suite#94]
I can't export to MTurk Crowd anymore, except with BBCode

**Comment by brandonhellman** [comment]
What is the error saying?

**Comment by mmbrown2000** [comment]
I'm sorry, I meant to come back and post that this was my fault. I didn't
realize there was a place where you have to answer about whether you want
to export the hit or not. Once I discovered and did that, it worked.

Thank you for checking,
Michele
