### ISSUE TITLE
Earnings on mturk page not updating

### ISSUE THREAD

**Issue by jeffreyshih11** [brandonhellman/mturk-suite#95]
The earnings amount next to Worker ID is no longer updating whenever I submit a HIT. Just started happening after new update. Just updated to Firefox 60.0.1 but same thing was happening before I updated.

**Comment by brandonhellman** [comment]
Just tested it on Firefox and can't replicate it. Do you mind giving me step by step on how to reproduce?

**Comment by jeffreyshih11** [comment]
logged into mturk, open up finder, accept HIT, complete and submit HIT. Typically would see the earnings increase by the value of the HIT but that's not longer the case. Sorry if it's vague.

**Comment by dljorgen** [comment]
I also use firefox and my earnings won't update since this morning either. I get an error that the address is not understood.  The address is as follows which seems to be chrome rather than firefox. 
chrome-extension://{dd19b0aa-6eee-4a10-a6bc-361a163f7821}/hit_tracker/hit_tracker.html

**Comment by jeffreyshih11** [comment]
^^ same address as above

**Comment by brandonhellman** [comment]
Just trying to be clear. You are expecting the values on the HIT Tracker page to update, not on the MTurk page.

**Comment by jeffreyshih11** [comment]
on the mturk page on the top left next to worker ID. sorry for not clarifying

**Comment by jbrown5886** [comment]
I am having the same issue. In the header of the dashboard page next to the worker ID the total only updates on a page refresh, not when a hit is submitted in a separate window.
