### ISSUE TITLE
Is it possible to adjust the audio volume of the voice readouts?

### ISSUE THREAD

**Issue by bmcg2201** [brandonhellman/mturk-suite#96]
For HIT Catcher/HIT Finder, the voices are just so much louder than anything else on my computer.  "HIT Caught/Include List Match Found" is what I'm referring too.  I love your apps and they are a life saver, this is the only thing I can think of to improve it.  Thanks for everything.

**Comment by brandonhellman** [comment]
This is something that will be coming, I think I'll bump this up sooner though since voice options should be a fairly easy thing. Expect it within the next two weeks.

**Comment by bmcg2201** [comment]
Awesome can't wait.
